/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linksUpsert } from "../../funcs/linksUpsert.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpsertLinkRequestBody$inboundSchema.optional(),
};

export const tool$linksUpsert: ToolDefinition<typeof args> = {
  name: "links_upsert",
  description: `Upsert a link

Upsert a link for the authenticated workspace by its URL. If a link with the same URL already exists, return it (or update it if there are any changes). Otherwise, a new link will be created.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await linksUpsert(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
