/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { partnersCreate } from "../../funcs/partnersCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreatePartnerRequestBody$inboundSchema.optional(),
};

export const tool$partnersCreate: ToolDefinition<typeof args> = {
  name: "partners_create",
  description: `Create a new partner

Create a new partner for a program. If partner exists, automatically enrolls them.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await partnersCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
