// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPatchLinksLinkID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "updateLink[0]":
			dir.HandlerFunc("updateLink", testUpdateLinkUpdateLink0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testUpdateLinkUpdateLink0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &components.LinkSchema{
		ID:              "<id>",
		Domain:          "tinted-nectarine.info",
		Key:             "<key>",
		URL:             "https://powerless-juggernaut.org",
		TrackConversion: types.Bool(false),
		ExternalID:      types.String("<id>"),
		TenantID:        types.String("<id>"),
		ProgramID:       types.String("<id>"),
		PartnerID:       types.String("<id>"),
		Archived:        types.Bool(false),
		ExpiresAt:       types.String("1746907077556"),
		ExpiredURL:      types.String("https://juvenile-exploration.biz"),
		Password:        types.String("kuMjbGhnJP7Bopu"),
		Proxy:           types.Bool(false),
		Title:           types.String("<value>"),
		Description:     types.String("bleak from that qualified cycle woot abseil perfumed"),
		Image:           types.String("https://loremflickr.com/1166/1632?lock=5920233536834378"),
		Video:           types.String("https://loremflickr.com/996/369?lock=4799093392417520"),
		Rewrite:         types.Bool(false),
		DoIndex:         types.Bool(false),
		Ios:             types.String("<value>"),
		Android:         types.String("<id>"),
		Geo:             &components.Geo{},
		PublicStats:     types.Bool(false),
		TagID:           types.String("<id>"),
		Tags: []components.TagSchema{
			components.TagSchema{
				ID:    "<id>",
				Name:  "<value>",
				Color: components.ColorBlue,
			},
			components.TagSchema{
				ID:    "<id>",
				Name:  "<value>",
				Color: components.ColorBlue,
			},
			components.TagSchema{
				ID:    "<id>",
				Name:  "<value>",
				Color: components.ColorGreen,
			},
		},
		FolderID:    types.String("<id>"),
		WebhookIds:  []string{},
		Comments:    types.String("duh clamour urgently voluntarily scale gut readies concerning statement nice consequently provided when rim league almost forenenst instead arbitrate pulse"),
		ShortLink:   "https://impossible-typeface.net/",
		QrCode:      "https://worthy-effector.net",
		UtmSource:   types.String("<value>"),
		UtmMedium:   types.String("<value>"),
		UtmCampaign: types.String("<value>"),
		UtmTerm:     types.String("<value>"),
		UtmContent:  types.String("<value>"),
		UserID:      types.String("<id>"),
		WorkspaceID: "<id>",
		Clicks:      types.Float64(0),
		LastClicked: types.String("<value>"),
		Leads:       types.Float64(0),
		Sales:       types.Float64(0),
		SaleAmount:  types.Float64(0),
		CreatedAt:   "1718485510854",
		UpdatedAt:   "1745130854965",
		ProjectID:   "<id>",
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
