// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetWorkspacesIDOrSlug(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "getWorkspace[0]":
			dir.HandlerFunc("getWorkspace", testGetWorkspaceGetWorkspace0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetWorkspaceGetWorkspace0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &components.WorkspaceSchema{
		ID:                "<id>",
		Name:              "<value>",
		Slug:              "<value>",
		Logo:              nil,
		InviteCode:        types.String("<value>"),
		Plan:              components.PlanBusinessMax,
		StripeID:          types.String("<id>"),
		BillingCycleStart: 5588.34,
		PaymentFailedAt:   types.String("<value>"),
		StripeConnectID:   types.String("<id>"),
		TotalLinks:        5442.21,
		Usage:             5212.35,
		UsageLimit:        9699.61,
		LinksUsage:        4580.49,
		LinksLimit:        4508.24,
		SalesUsage:        2627.95,
		SalesLimit:        2134.57,
		DomainsLimit:      9371.46,
		TagsLimit:         4381.42,
		FoldersUsage:      8013.73,
		FoldersLimit:      788.88,
		UsersLimit:        2199.56,
		AiUsage:           3134.64,
		AiLimit:           945.89,
		ConversionEnabled: false,
		DotLinkClaimed:    false,
		PartnersEnabled:   true,
		CreatedAt:         "1737210463283",
		Users: []components.Users{
			components.Users{
				Role:            components.RoleMember,
				DefaultFolderID: types.String("<id>"),
			},
			components.Users{
				Role:            components.RoleOwner,
				DefaultFolderID: types.String("<id>"),
			},
		},
		Domains: []components.Domains{
			components.Domains{
				Slug:     "acme.com",
				Primary:  types.Bool(false),
				Verified: types.Bool(false),
			},
		},
		Store: map[string]any{
			"key":  "<value>",
			"key1": "<value>",
		},
		AllowedHostnames: []string{
			"dub.sh",
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
