/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Dub } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Embed Tokens Create Referrals Embed Token", async () => {
  const testHttpClient = createTestHTTPClient("createReferralsEmbedToken");

  const dub = new Dub({
    httpClient: testHttpClient,
    token: "DUB_API_KEY",
  });

  const result = await dub.embedTokens.referrals();
  expect(result).toBeDefined();
  expect(result).toEqual({
    publicToken: "<value>",
    expires: "<value>",
  });
});
