/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Dub } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Qr Codes Get Qr Code", async () => {
  const testHttpClient = createTestHTTPClient("getQRCode");

  const dub = new Dub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    token: "DUB_API_KEY",
  });

  const result = await dub.qrCodes.get({
    url: "https://normal-making.name",
  });
  expect(result).toBeDefined();
  expect(result).toEqual("<value>");
});
