/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embedTokensCreate } from "../funcs/embedTokensCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EmbedTokens extends ClientSDK {
  /**
   * Create a new embed token
   *
   * @remarks
   * Create a new embed token for the referral link.
   */
  async create(
    request?: operations.CreateEmbedTokenRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateEmbedTokenResponseBody> {
    return unwrapAsync(embedTokensCreate(
      this,
      request,
      options,
    ));
  }
}
