/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { partnerApplicationsApprove } from "../funcs/partnerApplicationsApprove.js";
import { partnerApplicationsList } from "../funcs/partnerApplicationsList.js";
import { partnerApplicationsReject } from "../funcs/partnerApplicationsReject.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PartnerApplications extends ClientSDK {
  /**
   * List all pending partner applications
   *
   * @remarks
   * Retrieve a paginated list of pending applications for your partner program.
   */
  async list(
    request?: operations.ListPartnerApplicationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<operations.ListPartnerApplicationsResponseBody>> {
    return unwrapAsync(partnerApplicationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Approve a partner application
   *
   * @remarks
   * Approve a pending partner application to your program. The partner will be enrolled in the specified group and notified of the approval.
   */
  async approve(
    request: operations.ApprovePartnerRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ApprovePartnerResponseBody> {
    return unwrapAsync(partnerApplicationsApprove(
      this,
      request,
      options,
    ));
  }

  /**
   * Reject a partner application
   *
   * @remarks
   * Reject a pending partner application to your program. The partner will be notified via email that their application was not approved.
   */
  async reject(
    request: operations.RejectPartnerRequestBody,
    options?: RequestOptions,
  ): Promise<operations.RejectPartnerResponseBody> {
    return unwrapAsync(partnerApplicationsReject(
      this,
      request,
      options,
    ));
  }
}
