/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { programApplicationsApprove } from "../funcs/programApplicationsApprove.js";
import { programApplicationsList } from "../funcs/programApplicationsList.js";
import { programApplicationsReject } from "../funcs/programApplicationsReject.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ProgramApplications extends ClientSDK {
  /**
   * List all program applications
   *
   * @remarks
   * Retrieve a paginated list of applications for your partner program. Filter by `status` to list pending, approved, or rejected applications.
   */
  async list(
    request?: operations.ListProgramApplicationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<operations.ListProgramApplicationsResponseBody>> {
    return unwrapAsync(programApplicationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Approve a partner application
   *
   * @remarks
   * Approve a pending partner application to your program. The partner will be enrolled in the specified group and notified of the approval.
   */
  async approve(
    request: operations.ApproveProgramApplicationRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ApproveProgramApplicationResponseBody> {
    return unwrapAsync(programApplicationsApprove(
      this,
      request,
      options,
    ));
  }

  /**
   * Reject a partner application
   *
   * @remarks
   * Reject a pending partner application to your program. The partner will be notified via email that their application was not approved.
   */
  async reject(
    request: operations.RejectProgramApplicationRequestBody,
    options?: RequestOptions,
  ): Promise<operations.RejectProgramApplicationResponseBody> {
    return unwrapAsync(programApplicationsReject(
      this,
      request,
      options,
    ));
  }
}
