// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type GetCustomerRequest struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include expanded fields on the customer (`link`, `partner`, `discount`).
	IncludeExpandedFields *bool `queryParam:"style=form,explode=true,name=includeExpandedFields"`
}

func (o *GetCustomerRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerRequest) GetIncludeExpandedFields() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeExpandedFields
}

type GetCustomerLink struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key string `json:"key"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
}

func (o *GetCustomerLink) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerLink) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *GetCustomerLink) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *GetCustomerLink) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *GetCustomerLink) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

type GetCustomerPartner struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email"`
	Image *string `json:"image"`
}

func (o *GetCustomerPartner) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerPartner) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetCustomerPartner) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetCustomerPartner) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

type GetCustomerType string

const (
	GetCustomerTypePercentage GetCustomerType = "percentage"
	GetCustomerTypeFlat       GetCustomerType = "flat"
)

func (e GetCustomerType) ToPointer() *GetCustomerType {
	return &e
}
func (e *GetCustomerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percentage":
		fallthrough
	case "flat":
		*e = GetCustomerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCustomerType: %v", v)
	}
}

type GetCustomerDiscount struct {
	ID            string          `json:"id"`
	Amount        float64         `json:"amount"`
	Type          GetCustomerType `json:"type"`
	MaxDuration   *float64        `json:"maxDuration"`
	Description   *string         `json:"description,omitempty"`
	CouponID      *string         `json:"couponId"`
	CouponTestID  *string         `json:"couponTestId"`
	PartnersCount *float64        `json:"partnersCount,omitempty"`
}

func (o *GetCustomerDiscount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerDiscount) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *GetCustomerDiscount) GetType() GetCustomerType {
	if o == nil {
		return GetCustomerType("")
	}
	return o.Type
}

func (o *GetCustomerDiscount) GetMaxDuration() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxDuration
}

func (o *GetCustomerDiscount) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetCustomerDiscount) GetCouponID() *string {
	if o == nil {
		return nil
	}
	return o.CouponID
}

func (o *GetCustomerDiscount) GetCouponTestID() *string {
	if o == nil {
		return nil
	}
	return o.CouponTestID
}

func (o *GetCustomerDiscount) GetPartnersCount() *float64 {
	if o == nil {
		return nil
	}
	return o.PartnersCount
}

// GetCustomerResponseBody - The customer object.
type GetCustomerResponseBody struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `json:"id"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
	// Name of the customer.
	Name string `json:"name"`
	// Email of the customer.
	Email *string `json:"email,omitempty"`
	// Avatar URL of the customer.
	Avatar *string `json:"avatar,omitempty"`
	// Country of the customer.
	Country *string `json:"country,omitempty"`
	// The date the customer was created.
	CreatedAt string               `json:"createdAt"`
	Link      *GetCustomerLink     `json:"link,omitempty"`
	ProgramID *string              `json:"programId,omitempty"`
	Partner   *GetCustomerPartner  `json:"partner,omitempty"`
	Discount  *GetCustomerDiscount `json:"discount,omitempty"`
}

func (o *GetCustomerResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomerResponseBody) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *GetCustomerResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetCustomerResponseBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *GetCustomerResponseBody) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *GetCustomerResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *GetCustomerResponseBody) GetLink() *GetCustomerLink {
	if o == nil {
		return nil
	}
	return o.Link
}

func (o *GetCustomerResponseBody) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *GetCustomerResponseBody) GetPartner() *GetCustomerPartner {
	if o == nil {
		return nil
	}
	return o.Partner
}

func (o *GetCustomerResponseBody) GetDiscount() *GetCustomerDiscount {
	if o == nil {
		return nil
	}
	return o.Discount
}

type GetCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The customer object.
	Object *GetCustomerResponseBody
}

func (o *GetCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCustomerResponse) GetObject() *GetCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
