/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the dub SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx linksCreate.example.ts
 */

import { Dub } from "dub";

const dub = new Dub({
  token: "DUB_API_KEY",
});

async function main() {
  const result = await dub.links.create();

  console.log(result);
}

main().catch(console.error);
