workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-first-source:
        inputs:
            - location: https://api.dub.co
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dub/dub/my-first-source
targets:
    my-first-target:
        target: typescript
        source: my-first-source
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dub/dub/code-samples-typescript-my-first-target
