/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateDomainGlobals = {
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    workspaceId?: string | undefined;
};

export type CreateDomainRequestBody = {
    /**
     * Name of the domain.
     */
    slug: string;
    /**
     * Redirect users to a specific URL when any link under this domain has expired.
     */
    expiredUrl?: string | null | undefined;
    /**
     * Whether to archive this domain. `false` will unarchive a previously archived domain.
     */
    archived?: boolean | undefined;
    /**
     * Provide context to your teammates in the link creation modal by showing them an example of a link to be shortened.
     */
    placeholder?: string | null | undefined;
};

/** @internal */
export const CreateDomainGlobals$inboundSchema: z.ZodType<
    CreateDomainGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    workspaceId: z.string().optional(),
});

/** @internal */
export type CreateDomainGlobals$Outbound = {
    workspaceId?: string | undefined;
};

/** @internal */
export const CreateDomainGlobals$outboundSchema: z.ZodType<
    CreateDomainGlobals$Outbound,
    z.ZodTypeDef,
    CreateDomainGlobals
> = z.object({
    workspaceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDomainGlobals$ {
    /** @deprecated use `CreateDomainGlobals$inboundSchema` instead. */
    export const inboundSchema = CreateDomainGlobals$inboundSchema;
    /** @deprecated use `CreateDomainGlobals$outboundSchema` instead. */
    export const outboundSchema = CreateDomainGlobals$outboundSchema;
    /** @deprecated use `CreateDomainGlobals$Outbound` instead. */
    export type Outbound = CreateDomainGlobals$Outbound;
}

/** @internal */
export const CreateDomainRequestBody$inboundSchema: z.ZodType<
    CreateDomainRequestBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    slug: z.string(),
    expiredUrl: z.nullable(z.string()).optional(),
    archived: z.boolean().default(false),
    placeholder: z.nullable(z.string().default("https://dub.co/help/article/what-is-dub")),
});

/** @internal */
export type CreateDomainRequestBody$Outbound = {
    slug: string;
    expiredUrl?: string | null | undefined;
    archived: boolean;
    placeholder: string | null;
};

/** @internal */
export const CreateDomainRequestBody$outboundSchema: z.ZodType<
    CreateDomainRequestBody$Outbound,
    z.ZodTypeDef,
    CreateDomainRequestBody
> = z.object({
    slug: z.string(),
    expiredUrl: z.nullable(z.string()).optional(),
    archived: z.boolean().default(false),
    placeholder: z.nullable(z.string().default("https://dub.co/help/article/what-is-dub")),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDomainRequestBody$ {
    /** @deprecated use `CreateDomainRequestBody$inboundSchema` instead. */
    export const inboundSchema = CreateDomainRequestBody$inboundSchema;
    /** @deprecated use `CreateDomainRequestBody$outboundSchema` instead. */
    export const outboundSchema = CreateDomainRequestBody$outboundSchema;
    /** @deprecated use `CreateDomainRequestBody$Outbound` instead. */
    export type Outbound = CreateDomainRequestBody$Outbound;
}
