/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The unique IDs of the tags assigned to the short link.
 */
export type CreatePartnerTagIds = string | Array<string>;

/**
 * The unique name of the tags assigned to the short link (case insensitive).
 */
export type CreatePartnerTagNames = string | Array<string>;

export type CreatePartnerTestVariants = {
  url: string;
  percentage: number;
};

/**
 * Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.
 */
export type LinkProps = {
  /**
   * The length of the short link slug. Defaults to 7 if not provided. When used with `prefix`, the total length of the key will be `prefix.length + keyLength`.
   */
  keyLength?: number | undefined;
  /**
   * The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
   */
  externalId?: string | null | undefined;
  /**
   * The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
   */
  tenantId?: string | null | undefined;
  /**
   * The prefix of the short link slug for randomly-generated keys (e.g. if prefix is `/c/`, generated keys will be in the `/c/:key` format). Will be ignored if `key` is provided.
   */
  prefix?: string | undefined;
  /**
   * Whether the short link is archived. Defaults to `false` if not provided.
   */
  archived?: boolean | undefined;
  /**
   * The unique IDs of the tags assigned to the short link.
   */
  tagIds?: string | Array<string> | undefined;
  /**
   * The unique name of the tags assigned to the short link (case insensitive).
   */
  tagNames?: string | Array<string> | undefined;
  /**
   * The comments for the short link.
   */
  comments?: string | null | undefined;
  /**
   * The date and time when the short link will expire at.
   */
  expiresAt?: string | null | undefined;
  /**
   * The URL to redirect to when the short link has expired.
   */
  expiredUrl?: string | null | undefined;
  /**
   * The password required to access the destination URL of the short link.
   */
  password?: string | null | undefined;
  /**
   * Whether the short link uses Custom Link Previews feature. Defaults to `false` if not provided.
   */
  proxy?: boolean | undefined;
  /**
   * The custom link preview title (og:title). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
   */
  title?: string | null | undefined;
  /**
   * The custom link preview description (og:description). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
   */
  description?: string | null | undefined;
  /**
   * The custom link preview image (og:image). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
   */
  image?: string | null | undefined;
  /**
   * The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
   */
  video?: string | null | undefined;
  /**
   * Whether the short link uses link cloaking. Defaults to `false` if not provided.
   */
  rewrite?: boolean | undefined;
  /**
   * The iOS destination URL for the short link for iOS device targeting.
   */
  ios?: string | null | undefined;
  /**
   * The Android destination URL for the short link for Android device targeting.
   */
  android?: string | null | undefined;
  /**
   * Allow search engines to index your short link. Defaults to `false` if not provided. Learn more: https://d.to/noindex
   */
  doIndex?: boolean | undefined;
  /**
   * An array of A/B test URLs and the percentage of traffic to send to each URL.
   */
  testVariants?: Array<CreatePartnerTestVariants> | null | undefined;
  /**
   * The date and time when the tests started.
   */
  testStartedAt?: string | null | undefined;
  /**
   * The date and time when the tests were or will be completed.
   */
  testCompletedAt?: string | null | undefined;
};

export type CreatePartnerRequestBody = {
  /**
   * The partner's full name. If undefined, the partner's email will be used in lieu of their name (e.g. `john@acme.com`)
   */
  name?: string | null | undefined;
  /**
   * The partner's email address. Partners will be able to claim their profile by signing up at `partners.dub.co` with this email.
   */
  email: string;
  /**
   * The partner's unique username in your system (max 100 characters). This will be used to create a short link for the partner using your program's default domain. If not provided, Dub will try to generate a username from the partner's name or email.
   */
  username?: string | null | undefined;
  /**
   * The partner's avatar image. If not provided, a default avatar will be used.
   */
  image?: string | null | undefined;
  /**
   * The partner's unique ID in your system. Useful for retrieving the partner's links and stats later on. If not provided, the partner will be created as a standalone partner.
   */
  tenantId?: string | undefined;
  /**
   * The group ID to add the partner to. If not provided, the partner will be added to the default group.
   */
  groupId?: string | undefined;
  /**
   * The partner's country of residence. Must be passed as a 2-letter ISO 3166-1 country code. See https://d.to/geo for more information.
   */
  country?: string | null | undefined;
  /**
   * A brief description of the partner and their background. Max 5,000 characters.
   */
  description?: string | null | undefined;
  /**
   * Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.
   */
  linkProps?: LinkProps | undefined;
};

/**
 * The status of the partner's enrollment in the program.
 */
export const CreatePartnerStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Invited: "invited",
  Declined: "declined",
  Deactivated: "deactivated",
  Banned: "banned",
  Archived: "archived",
} as const;
/**
 * The status of the partner's enrollment in the program.
 */
export type CreatePartnerStatus = ClosedEnum<typeof CreatePartnerStatus>;

export type Links = {
  /**
   * The unique ID of the short link.
   */
  id: string;
  /**
   * The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
   */
  domain: string;
  /**
   * The short link slug. If not provided, a random 7-character slug will be generated.
   */
  key: string;
  /**
   * The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
   */
  shortLink: string;
  /**
   * The destination URL of the short link.
   */
  url: string;
  /**
   * The number of clicks on the short link.
   */
  clicks: number;
  /**
   * The number of leads the short link has generated.
   */
  leads: number;
  /**
   * The number of leads that converted to paying customers.
   */
  conversions: number;
  /**
   * The total number of sales (includes recurring sales) generated by the short link.
   */
  sales: number;
  /**
   * The total dollar value of sales (in cents) generated by the short link.
   */
  saleAmount: number;
};

/**
 * If the partner was banned from the program, this is the reason for the ban.
 */
export const BannedReason = {
  TosViolation: "tos_violation",
  InappropriateContent: "inappropriate_content",
  FakeTraffic: "fake_traffic",
  Fraud: "fraud",
  Spam: "spam",
  BrandAbuse: "brand_abuse",
} as const;
/**
 * If the partner was banned from the program, this is the reason for the ban.
 */
export type BannedReason = ClosedEnum<typeof BannedReason>;

export type Eight = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "phone";
};

export type Seven = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "number";
};

export type FieldsOptions = {
  label: string;
  value: string;
};

export type Six = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "multiSelect";
  options: Array<FieldsOptions>;
};

export type Five = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "date";
};

export type Fields4 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "country";
};

export type Options = {
  label: string;
  value: string;
};

export type Fields3 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "select";
  options: Array<Options>;
};

export type FieldsConstraints = {
  maxLength?: number | undefined;
};

export type Fields2 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "textarea";
  constraints?: FieldsConstraints | undefined;
};

export type Constraints = {
  maxLength?: number | undefined;
  pattern?: string | undefined;
};

export type Fields1 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "text";
  constraints?: Constraints | undefined;
};

export type Fields =
  | Fields1
  | Fields2
  | Fields3
  | Fields4
  | Five
  | Six
  | Seven
  | Eight;

export type ReferralFormData = {
  fields: Array<
    Fields1 | Fields2 | Fields3 | Fields4 | Five | Six | Seven | Eight
  >;
};

/**
 * The created or updated partner
 */
export type CreatePartnerResponseBody = {
  /**
   * The partner's unique ID on Dub.
   */
  id: string;
  /**
   * The partner's full legal name.
   */
  name: string;
  /**
   * If the partner profile type is a company, this is the partner's legal company name.
   */
  companyName: string | null;
  /**
   * The partner's email address. Should be a unique value across Dub.
   */
  email: string | null;
  /**
   * The partner's avatar image.
   */
  image: string | null;
  /**
   * A brief description of the partner and their background.
   */
  description?: string | null | undefined;
  /**
   * The partner's country (required for tax purposes).
   */
  country: string | null;
  /**
   * The partner's PayPal email (for receiving payouts via PayPal).
   */
  paypalEmail: string | null;
  /**
   * The partner's Stripe Connect ID (for receiving payouts via Stripe).
   */
  stripeConnectId: string | null;
  /**
   * The date when the partner enabled payouts.
   */
  payoutsEnabledAt: string | null;
  /**
   * The date when the partner received the trusted badge in the partner network.
   */
  trustedAt: string | null;
  /**
   * The program's unique ID on Dub.
   */
  programId: string;
  /**
   * The partner's group ID on Dub.
   */
  groupId?: string | null | undefined;
  /**
   * The partner's unique ID on Dub.
   */
  partnerId: string;
  /**
   * The partner's unique ID within your database. Can be useful for associating the partner with a user in your database and retrieving/update their data in the future.
   */
  tenantId: string | null;
  createdAt: string;
  /**
   * The status of the partner's enrollment in the program.
   */
  status: CreatePartnerStatus;
  /**
   * The partner's referral links in this program.
   */
  links: Array<Links> | null;
  /**
   * The total commissions paid to the partner for their referrals
   */
  totalCommissions: number;
  clickRewardId?: string | null | undefined;
  leadRewardId?: string | null | undefined;
  saleRewardId?: string | null | undefined;
  discountId?: string | null | undefined;
  /**
   * If the partner submitted an application to join the program, this is the ID of the application.
   */
  applicationId?: string | null | undefined;
  /**
   * If the partner was banned from the program, this is the date of the ban.
   */
  bannedAt?: string | null | undefined;
  /**
   * If the partner was banned from the program, this is the reason for the ban.
   */
  bannedReason?: BannedReason | null | undefined;
  referralFormData?: ReferralFormData | null | undefined;
  /**
   * The total number of clicks on the partner's links
   */
  totalClicks: number;
  /**
   * The total number of leads generated by the partner's links
   */
  totalLeads: number;
  /**
   * The total number of leads that converted to paying customers
   */
  totalConversions: number;
  /**
   * The total number of sales generated by the partner's links (includes recurring sales)
   */
  totalSales: number;
  /**
   * Total revenue generated by the partner's links
   */
  totalSaleAmount: number;
  /**
   * Net revenue after commissions (`Total Revenue - Total Commissions`)
   */
  netRevenue: number;
  /**
   * Earnings Per Click (EPC) (`Total Revenue ÷ Total Clicks`)
   */
  earningsPerClick?: number | null | undefined;
  /**
   * Average lifetime value for each paying customer (`Total Revenue ÷ Total Conversions`)
   */
  averageLifetimeValue?: number | null | undefined;
  /**
   * Percentage of clicks that become leads (`Total Leads ÷ Total Clicks`)
   */
  clickToLeadRate?: number | null | undefined;
  /**
   * Percentage of clicks that convert to paying customers (`Total Conversions ÷ Total Clicks`)
   */
  clickToConversionRate?: number | null | undefined;
  /**
   * Percentage of leads that convert to paying customers (`Total Conversions ÷ Total Leads`)
   */
  leadToConversionRate?: number | null | undefined;
  /**
   * Return On Ad Spend (ROAS) (`Total Revenue ÷ Total Commissions`)
   */
  returnOnAdSpend?: number | null | undefined;
  /**
   * The partner's website URL (including the https protocol).
   */
  website?: string | null | undefined;
  /**
   * The partner's YouTube channel username (e.g. `johndoe`).
   */
  youtube?: string | null | undefined;
  /**
   * The partner's Twitter username (e.g. `johndoe`).
   */
  twitter?: string | null | undefined;
  /**
   * The partner's LinkedIn username (e.g. `johndoe`).
   */
  linkedin?: string | null | undefined;
  /**
   * The partner's Instagram username (e.g. `johndoe`).
   */
  instagram?: string | null | undefined;
  /**
   * The partner's TikTok username (e.g. `johndoe`).
   */
  tiktok?: string | null | undefined;
};

/** @internal */
export type CreatePartnerTagIds$Outbound = string | Array<string>;

/** @internal */
export const CreatePartnerTagIds$outboundSchema: z.ZodType<
  CreatePartnerTagIds$Outbound,
  z.ZodTypeDef,
  CreatePartnerTagIds
> = z.union([z.string(), z.array(z.string())]);

export function createPartnerTagIdsToJSON(
  createPartnerTagIds: CreatePartnerTagIds,
): string {
  return JSON.stringify(
    CreatePartnerTagIds$outboundSchema.parse(createPartnerTagIds),
  );
}

/** @internal */
export type CreatePartnerTagNames$Outbound = string | Array<string>;

/** @internal */
export const CreatePartnerTagNames$outboundSchema: z.ZodType<
  CreatePartnerTagNames$Outbound,
  z.ZodTypeDef,
  CreatePartnerTagNames
> = z.union([z.string(), z.array(z.string())]);

export function createPartnerTagNamesToJSON(
  createPartnerTagNames: CreatePartnerTagNames,
): string {
  return JSON.stringify(
    CreatePartnerTagNames$outboundSchema.parse(createPartnerTagNames),
  );
}

/** @internal */
export type CreatePartnerTestVariants$Outbound = {
  url: string;
  percentage: number;
};

/** @internal */
export const CreatePartnerTestVariants$outboundSchema: z.ZodType<
  CreatePartnerTestVariants$Outbound,
  z.ZodTypeDef,
  CreatePartnerTestVariants
> = z.object({
  url: z.string(),
  percentage: z.number(),
});

export function createPartnerTestVariantsToJSON(
  createPartnerTestVariants: CreatePartnerTestVariants,
): string {
  return JSON.stringify(
    CreatePartnerTestVariants$outboundSchema.parse(createPartnerTestVariants),
  );
}

/** @internal */
export type LinkProps$Outbound = {
  keyLength?: number | undefined;
  externalId?: string | null | undefined;
  tenantId?: string | null | undefined;
  prefix?: string | undefined;
  archived?: boolean | undefined;
  tagIds?: string | Array<string> | undefined;
  tagNames?: string | Array<string> | undefined;
  comments?: string | null | undefined;
  expiresAt?: string | null | undefined;
  expiredUrl?: string | null | undefined;
  password?: string | null | undefined;
  proxy?: boolean | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
  image?: string | null | undefined;
  video?: string | null | undefined;
  rewrite?: boolean | undefined;
  ios?: string | null | undefined;
  android?: string | null | undefined;
  doIndex?: boolean | undefined;
  testVariants?: Array<CreatePartnerTestVariants$Outbound> | null | undefined;
  testStartedAt?: string | null | undefined;
  testCompletedAt?: string | null | undefined;
};

/** @internal */
export const LinkProps$outboundSchema: z.ZodType<
  LinkProps$Outbound,
  z.ZodTypeDef,
  LinkProps
> = z.object({
  keyLength: z.number().optional(),
  externalId: z.nullable(z.string()).optional(),
  tenantId: z.nullable(z.string()).optional(),
  prefix: z.string().optional(),
  archived: z.boolean().optional(),
  tagIds: z.union([z.string(), z.array(z.string())]).optional(),
  tagNames: z.union([z.string(), z.array(z.string())]).optional(),
  comments: z.nullable(z.string()).optional(),
  expiresAt: z.nullable(z.string()).optional(),
  expiredUrl: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  proxy: z.boolean().optional(),
  title: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  image: z.nullable(z.string()).optional(),
  video: z.nullable(z.string()).optional(),
  rewrite: z.boolean().optional(),
  ios: z.nullable(z.string()).optional(),
  android: z.nullable(z.string()).optional(),
  doIndex: z.boolean().optional(),
  testVariants: z.nullable(
    z.array(z.lazy(() => CreatePartnerTestVariants$outboundSchema)),
  ).optional(),
  testStartedAt: z.nullable(z.string()).optional(),
  testCompletedAt: z.nullable(z.string()).optional(),
});

export function linkPropsToJSON(linkProps: LinkProps): string {
  return JSON.stringify(LinkProps$outboundSchema.parse(linkProps));
}

/** @internal */
export type CreatePartnerRequestBody$Outbound = {
  name?: string | null | undefined;
  email: string;
  username?: string | null | undefined;
  image?: string | null | undefined;
  tenantId?: string | undefined;
  groupId?: string | undefined;
  country?: string | null | undefined;
  description?: string | null | undefined;
  linkProps?: LinkProps$Outbound | undefined;
};

/** @internal */
export const CreatePartnerRequestBody$outboundSchema: z.ZodType<
  CreatePartnerRequestBody$Outbound,
  z.ZodTypeDef,
  CreatePartnerRequestBody
> = z.object({
  name: z.nullable(z.string()).optional(),
  email: z.string(),
  username: z.nullable(z.string()).optional(),
  image: z.nullable(z.string()).optional(),
  tenantId: z.string().optional(),
  groupId: z.string().optional(),
  country: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  linkProps: z.lazy(() => LinkProps$outboundSchema).optional(),
});

export function createPartnerRequestBodyToJSON(
  createPartnerRequestBody: CreatePartnerRequestBody,
): string {
  return JSON.stringify(
    CreatePartnerRequestBody$outboundSchema.parse(createPartnerRequestBody),
  );
}

/** @internal */
export const CreatePartnerStatus$inboundSchema: z.ZodNativeEnum<
  typeof CreatePartnerStatus
> = z.nativeEnum(CreatePartnerStatus);

/** @internal */
export const Links$inboundSchema: z.ZodType<Links, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    domain: z.string(),
    key: z.string(),
    shortLink: z.string(),
    url: z.string(),
    clicks: z.number().default(0),
    leads: z.number().default(0),
    conversions: z.number().default(0),
    sales: z.number().default(0),
    saleAmount: z.number().default(0),
  });

export function linksFromJSON(
  jsonString: string,
): SafeParseResult<Links, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Links$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Links' from JSON`,
  );
}

/** @internal */
export const BannedReason$inboundSchema: z.ZodNativeEnum<typeof BannedReason> =
  z.nativeEnum(BannedReason);

/** @internal */
export const Eight$inboundSchema: z.ZodType<Eight, z.ZodTypeDef, unknown> = z
  .object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("phone"),
  });

export function eightFromJSON(
  jsonString: string,
): SafeParseResult<Eight, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eight$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eight' from JSON`,
  );
}

/** @internal */
export const Seven$inboundSchema: z.ZodType<Seven, z.ZodTypeDef, unknown> = z
  .object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("number"),
  });

export function sevenFromJSON(
  jsonString: string,
): SafeParseResult<Seven, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Seven$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Seven' from JSON`,
  );
}

/** @internal */
export const FieldsOptions$inboundSchema: z.ZodType<
  FieldsOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  value: z.string(),
});

export function fieldsOptionsFromJSON(
  jsonString: string,
): SafeParseResult<FieldsOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldsOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldsOptions' from JSON`,
  );
}

/** @internal */
export const Six$inboundSchema: z.ZodType<Six, z.ZodTypeDef, unknown> = z
  .object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("multiSelect"),
    options: z.array(z.lazy(() => FieldsOptions$inboundSchema)),
  });

export function sixFromJSON(
  jsonString: string,
): SafeParseResult<Six, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Six$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Six' from JSON`,
  );
}

/** @internal */
export const Five$inboundSchema: z.ZodType<Five, z.ZodTypeDef, unknown> = z
  .object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("date"),
  });

export function fiveFromJSON(
  jsonString: string,
): SafeParseResult<Five, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Five$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Five' from JSON`,
  );
}

/** @internal */
export const Fields4$inboundSchema: z.ZodType<Fields4, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("country"),
  });

export function fields4FromJSON(
  jsonString: string,
): SafeParseResult<Fields4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields4' from JSON`,
  );
}

/** @internal */
export const Options$inboundSchema: z.ZodType<Options, z.ZodTypeDef, unknown> =
  z.object({
    label: z.string(),
    value: z.string(),
  });

export function optionsFromJSON(
  jsonString: string,
): SafeParseResult<Options, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Options$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Options' from JSON`,
  );
}

/** @internal */
export const Fields3$inboundSchema: z.ZodType<Fields3, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("select"),
    options: z.array(z.lazy(() => Options$inboundSchema)),
  });

export function fields3FromJSON(
  jsonString: string,
): SafeParseResult<Fields3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields3' from JSON`,
  );
}

/** @internal */
export const FieldsConstraints$inboundSchema: z.ZodType<
  FieldsConstraints,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxLength: z.number().int().optional(),
});

export function fieldsConstraintsFromJSON(
  jsonString: string,
): SafeParseResult<FieldsConstraints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldsConstraints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldsConstraints' from JSON`,
  );
}

/** @internal */
export const Fields2$inboundSchema: z.ZodType<Fields2, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("textarea"),
    constraints: z.lazy(() => FieldsConstraints$inboundSchema).optional(),
  });

export function fields2FromJSON(
  jsonString: string,
): SafeParseResult<Fields2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields2' from JSON`,
  );
}

/** @internal */
export const Constraints$inboundSchema: z.ZodType<
  Constraints,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxLength: z.number().int().optional(),
  pattern: z.string().optional(),
});

export function constraintsFromJSON(
  jsonString: string,
): SafeParseResult<Constraints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Constraints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Constraints' from JSON`,
  );
}

/** @internal */
export const Fields1$inboundSchema: z.ZodType<Fields1, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("text"),
    constraints: z.lazy(() => Constraints$inboundSchema).optional(),
  });

export function fields1FromJSON(
  jsonString: string,
): SafeParseResult<Fields1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields1' from JSON`,
  );
}

/** @internal */
export const Fields$inboundSchema: z.ZodType<Fields, z.ZodTypeDef, unknown> = z
  .union([
    z.lazy(() => Fields1$inboundSchema),
    z.lazy(() => Fields2$inboundSchema),
    z.lazy(() => Fields3$inboundSchema),
    z.lazy(() => Fields4$inboundSchema),
    z.lazy(() => Five$inboundSchema),
    z.lazy(() => Six$inboundSchema),
    z.lazy(() => Seven$inboundSchema),
    z.lazy(() => Eight$inboundSchema),
  ]);

export function fieldsFromJSON(
  jsonString: string,
): SafeParseResult<Fields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields' from JSON`,
  );
}

/** @internal */
export const ReferralFormData$inboundSchema: z.ZodType<
  ReferralFormData,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.array(
    z.union([
      z.lazy(() => Fields1$inboundSchema),
      z.lazy(() => Fields2$inboundSchema),
      z.lazy(() => Fields3$inboundSchema),
      z.lazy(() => Fields4$inboundSchema),
      z.lazy(() => Five$inboundSchema),
      z.lazy(() => Six$inboundSchema),
      z.lazy(() => Seven$inboundSchema),
      z.lazy(() => Eight$inboundSchema),
    ]),
  ),
});

export function referralFormDataFromJSON(
  jsonString: string,
): SafeParseResult<ReferralFormData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReferralFormData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReferralFormData' from JSON`,
  );
}

/** @internal */
export const CreatePartnerResponseBody$inboundSchema: z.ZodType<
  CreatePartnerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  companyName: z.nullable(z.string()),
  email: z.nullable(z.string()),
  image: z.nullable(z.string()),
  description: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()),
  paypalEmail: z.nullable(z.string()),
  stripeConnectId: z.nullable(z.string()),
  payoutsEnabledAt: z.nullable(z.string()),
  trustedAt: z.nullable(z.string()),
  programId: z.string(),
  groupId: z.nullable(z.string()).optional(),
  partnerId: z.string(),
  tenantId: z.nullable(z.string()),
  createdAt: z.string(),
  status: CreatePartnerStatus$inboundSchema,
  links: z.nullable(z.array(z.lazy(() => Links$inboundSchema))),
  totalCommissions: z.number().default(0),
  clickRewardId: z.nullable(z.string()).optional(),
  leadRewardId: z.nullable(z.string()).optional(),
  saleRewardId: z.nullable(z.string()).optional(),
  discountId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
  bannedAt: z.nullable(z.string()).optional(),
  bannedReason: z.nullable(BannedReason$inboundSchema).optional(),
  referralFormData: z.nullable(z.lazy(() => ReferralFormData$inboundSchema))
    .optional(),
  totalClicks: z.number().default(0),
  totalLeads: z.number().default(0),
  totalConversions: z.number().default(0),
  totalSales: z.number().default(0),
  totalSaleAmount: z.number().default(0),
  netRevenue: z.number().default(0),
  earningsPerClick: z.nullable(z.number()).optional(),
  averageLifetimeValue: z.nullable(z.number()).optional(),
  clickToLeadRate: z.nullable(z.number()).optional(),
  clickToConversionRate: z.nullable(z.number()).optional(),
  leadToConversionRate: z.nullable(z.number()).optional(),
  returnOnAdSpend: z.nullable(z.number()).optional(),
  website: z.nullable(z.string()).optional(),
  youtube: z.nullable(z.string()).optional(),
  twitter: z.nullable(z.string()).optional(),
  linkedin: z.nullable(z.string()).optional(),
  instagram: z.nullable(z.string()).optional(),
  tiktok: z.nullable(z.string()).optional(),
});

export function createPartnerResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreatePartnerResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePartnerResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePartnerResponseBody' from JSON`,
  );
}
