/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetLinkInfoRequest = {
  domain?: string | undefined;
  /**
   * The key of the link to retrieve. E.g. for `d.to/github`, the key is `github`.
   */
  key?: string | undefined;
  /**
   * The unique ID of the short link.
   */
  linkId?: string | undefined;
  /**
   * This is the ID of the link in the your database.
   */
  externalId?: string | undefined;
};

/** @internal */
export type GetLinkInfoRequest$Outbound = {
  domain?: string | undefined;
  key?: string | undefined;
  linkId?: string | undefined;
  externalId?: string | undefined;
};

/** @internal */
export const GetLinkInfoRequest$outboundSchema: z.ZodType<
  GetLinkInfoRequest$Outbound,
  z.ZodTypeDef,
  GetLinkInfoRequest
> = z.object({
  domain: z.string().optional(),
  key: z.string().optional(),
  linkId: z.string().optional(),
  externalId: z.string().optional(),
});

export function getLinkInfoRequestToJSON(
  getLinkInfoRequest: GetLinkInfoRequest,
): string {
  return JSON.stringify(
    GetLinkInfoRequest$outboundSchema.parse(getLinkInfoRequest),
  );
}
