/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetTagsGlobals = {
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    workspaceId?: string | undefined;
};

export type GetTagsRequest = {};

/** @internal */
export const GetTagsGlobals$inboundSchema: z.ZodType<GetTagsGlobals, z.ZodTypeDef, unknown> =
    z.object({
        workspaceId: z.string().optional(),
    });

/** @internal */
export type GetTagsGlobals$Outbound = {
    workspaceId?: string | undefined;
};

/** @internal */
export const GetTagsGlobals$outboundSchema: z.ZodType<
    GetTagsGlobals$Outbound,
    z.ZodTypeDef,
    GetTagsGlobals
> = z.object({
    workspaceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTagsGlobals$ {
    /** @deprecated use `GetTagsGlobals$inboundSchema` instead. */
    export const inboundSchema = GetTagsGlobals$inboundSchema;
    /** @deprecated use `GetTagsGlobals$outboundSchema` instead. */
    export const outboundSchema = GetTagsGlobals$outboundSchema;
    /** @deprecated use `GetTagsGlobals$Outbound` instead. */
    export type Outbound = GetTagsGlobals$Outbound;
}

/** @internal */
export const GetTagsRequest$inboundSchema: z.ZodType<GetTagsRequest, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type GetTagsRequest$Outbound = {};

/** @internal */
export const GetTagsRequest$outboundSchema: z.ZodType<
    GetTagsRequest$Outbound,
    z.ZodTypeDef,
    GetTagsRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTagsRequest$ {
    /** @deprecated use `GetTagsRequest$inboundSchema` instead. */
    export const inboundSchema = GetTagsRequest$inboundSchema;
    /** @deprecated use `GetTagsRequest$outboundSchema` instead. */
    export const outboundSchema = GetTagsRequest$outboundSchema;
    /** @deprecated use `GetTagsRequest$Outbound` instead. */
    export type Outbound = GetTagsRequest$Outbound;
}
