/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A filter on the list based on the partner's `status` field.
 */
export const ListPartnersQueryParamStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Invited: "invited",
  Declined: "declined",
  Deactivated: "deactivated",
  Banned: "banned",
  Archived: "archived",
} as const;
/**
 * A filter on the list based on the partner's `status` field.
 */
export type ListPartnersQueryParamStatus = ClosedEnum<
  typeof ListPartnersQueryParamStatus
>;

/**
 * The field to sort the partners by. The default is `totalSaleAmount`.
 */
export const ListPartnersQueryParamSortBy = {
  CreatedAt: "createdAt",
  TotalClicks: "totalClicks",
  TotalLeads: "totalLeads",
  TotalConversions: "totalConversions",
  TotalSaleAmount: "totalSaleAmount",
  TotalCommissions: "totalCommissions",
  NetRevenue: "netRevenue",
  EarningsPerClick: "earningsPerClick",
  AverageLifetimeValue: "averageLifetimeValue",
  ClickToLeadRate: "clickToLeadRate",
  ClickToConversionRate: "clickToConversionRate",
  LeadToConversionRate: "leadToConversionRate",
  ReturnOnAdSpend: "returnOnAdSpend",
} as const;
/**
 * The field to sort the partners by. The default is `totalSaleAmount`.
 */
export type ListPartnersQueryParamSortBy = ClosedEnum<
  typeof ListPartnersQueryParamSortBy
>;

/**
 * The sort order. The default is `desc`.
 */
export const ListPartnersQueryParamSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The sort order. The default is `desc`.
 */
export type ListPartnersQueryParamSortOrder = ClosedEnum<
  typeof ListPartnersQueryParamSortOrder
>;

export type ListPartnersRequest = {
  /**
   * A filter on the list based on the partner's `status` field.
   */
  status?: ListPartnersQueryParamStatus | undefined;
  /**
   * A filter on the list based on the partner's `country` field.
   */
  country?: string | undefined;
  /**
   * The field to sort the partners by. The default is `totalSaleAmount`.
   */
  sortBy?: ListPartnersQueryParamSortBy | undefined;
  /**
   * The sort order. The default is `desc`.
   */
  sortOrder?: ListPartnersQueryParamSortOrder | undefined;
  /**
   * Filter the partner list based on the partner's `email`. The value must be a string. Takes precedence over `search`.
   */
  email?: string | undefined;
  /**
   * Filter the partner list based on the partner's `tenantId`. The value must be a string. Takes precedence over `email` and `search`.
   */
  tenantId?: string | undefined;
  /**
   * A search query to filter partners by ID, name, email, or link.
   */
  search?: string | undefined;
  /**
   * The page number for pagination.
   */
  page?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

/**
 * The status of the partner's enrollment in the program.
 */
export const ListPartnersStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Invited: "invited",
  Declined: "declined",
  Deactivated: "deactivated",
  Banned: "banned",
  Archived: "archived",
} as const;
/**
 * The status of the partner's enrollment in the program.
 */
export type ListPartnersStatus = ClosedEnum<typeof ListPartnersStatus>;

export type ListPartnersLinks = {
  /**
   * The unique ID of the short link.
   */
  id: string;
  /**
   * The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
   */
  domain: string;
  /**
   * The short link slug. If not provided, a random 7-character slug will be generated.
   */
  key: string;
  /**
   * The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
   */
  shortLink: string;
  /**
   * The destination URL of the short link.
   */
  url: string;
  /**
   * The number of clicks on the short link.
   */
  clicks: number;
  /**
   * The number of leads the short link has generated.
   */
  leads: number;
  /**
   * The number of leads that converted to paying customers.
   */
  conversions: number;
  /**
   * The total number of sales (includes recurring sales) generated by the short link.
   */
  sales: number;
  /**
   * The total dollar value of sales (in cents) generated by the short link.
   */
  saleAmount: number;
};

/**
 * If the partner was banned from the program, this is the reason for the ban.
 */
export const ListPartnersBannedReason = {
  TosViolation: "tos_violation",
  InappropriateContent: "inappropriate_content",
  FakeTraffic: "fake_traffic",
  Fraud: "fraud",
  Spam: "spam",
  BrandAbuse: "brand_abuse",
} as const;
/**
 * If the partner was banned from the program, this is the reason for the ban.
 */
export type ListPartnersBannedReason = ClosedEnum<
  typeof ListPartnersBannedReason
>;

export type Fields8 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "phone";
};

export type Fields7 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "number";
};

export type ListPartnersFieldsPartnersOptions = {
  label: string;
  value: string;
};

export type Fields6 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "multiSelect";
  options: Array<ListPartnersFieldsPartnersOptions>;
};

export type Fields5 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "date";
};

export type ListPartnersFields4 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "country";
};

export type ListPartnersFieldsOptions = {
  label: string;
  value: string;
};

export type ListPartnersFields3 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "select";
  options: Array<ListPartnersFieldsOptions>;
};

export type ListPartnersFieldsPartnersConstraints = {
  maxLength?: number | undefined;
};

export type ListPartnersFields2 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "textarea";
  constraints?: ListPartnersFieldsPartnersConstraints | undefined;
};

export type ListPartnersFieldsConstraints = {
  maxLength?: number | undefined;
  pattern?: string | undefined;
};

export type ListPartnersFields1 = {
  key: string;
  label: string;
  required: boolean;
  locked: boolean;
  position: number;
  type: "text";
  constraints?: ListPartnersFieldsConstraints | undefined;
};

export type ListPartnersFields =
  | ListPartnersFields1
  | ListPartnersFields2
  | ListPartnersFields3
  | ListPartnersFields4
  | Fields5
  | Fields6
  | Fields7
  | Fields8;

export type ListPartnersReferralFormData = {
  fields: Array<
    | ListPartnersFields1
    | ListPartnersFields2
    | ListPartnersFields3
    | ListPartnersFields4
    | Fields5
    | Fields6
    | Fields7
    | Fields8
  >;
};

export type ListPartnersResponseBody = {
  /**
   * The partner's unique ID on Dub.
   */
  id: string;
  /**
   * The partner's full legal name.
   */
  name: string;
  /**
   * If the partner profile type is a company, this is the partner's legal company name.
   */
  companyName: string | null;
  /**
   * The partner's email address. Should be a unique value across Dub.
   */
  email: string | null;
  /**
   * The partner's avatar image.
   */
  image: string | null;
  /**
   * A brief description of the partner and their background.
   */
  description?: string | null | undefined;
  /**
   * The partner's country (required for tax purposes).
   */
  country: string | null;
  /**
   * The partner's PayPal email (for receiving payouts via PayPal).
   */
  paypalEmail: string | null;
  /**
   * The partner's Stripe Connect ID (for receiving payouts via Stripe).
   */
  stripeConnectId: string | null;
  /**
   * The date when the partner enabled payouts.
   */
  payoutsEnabledAt: string | null;
  /**
   * The date when the partner received the trusted badge in the partner network.
   */
  trustedAt: string | null;
  /**
   * The program's unique ID on Dub.
   */
  programId: string;
  /**
   * The partner's group ID on Dub.
   */
  groupId?: string | null | undefined;
  /**
   * The partner's unique ID on Dub.
   */
  partnerId: string;
  /**
   * The partner's unique ID within your database. Can be useful for associating the partner with a user in your database and retrieving/update their data in the future.
   */
  tenantId: string | null;
  createdAt: string;
  /**
   * The status of the partner's enrollment in the program.
   */
  status: ListPartnersStatus;
  /**
   * The partner's referral links in this program.
   */
  links: Array<ListPartnersLinks> | null;
  /**
   * The total commissions paid to the partner for their referrals
   */
  totalCommissions: number;
  clickRewardId?: string | null | undefined;
  leadRewardId?: string | null | undefined;
  saleRewardId?: string | null | undefined;
  discountId?: string | null | undefined;
  /**
   * If the partner submitted an application to join the program, this is the ID of the application.
   */
  applicationId?: string | null | undefined;
  /**
   * If the partner was banned from the program, this is the date of the ban.
   */
  bannedAt?: string | null | undefined;
  /**
   * If the partner was banned from the program, this is the reason for the ban.
   */
  bannedReason?: ListPartnersBannedReason | null | undefined;
  referralFormData?: ListPartnersReferralFormData | null | undefined;
  /**
   * The total number of clicks on the partner's links
   */
  totalClicks: number;
  /**
   * The total number of leads generated by the partner's links
   */
  totalLeads: number;
  /**
   * The total number of leads that converted to paying customers
   */
  totalConversions: number;
  /**
   * The total number of sales generated by the partner's links (includes recurring sales)
   */
  totalSales: number;
  /**
   * Total revenue generated by the partner's links
   */
  totalSaleAmount: number;
  /**
   * Net revenue after commissions (`Total Revenue - Total Commissions`)
   */
  netRevenue: number;
  /**
   * Earnings Per Click (EPC) (`Total Revenue ÷ Total Clicks`)
   */
  earningsPerClick?: number | null | undefined;
  /**
   * Average lifetime value for each paying customer (`Total Revenue ÷ Total Conversions`)
   */
  averageLifetimeValue?: number | null | undefined;
  /**
   * Percentage of clicks that become leads (`Total Leads ÷ Total Clicks`)
   */
  clickToLeadRate?: number | null | undefined;
  /**
   * Percentage of clicks that convert to paying customers (`Total Conversions ÷ Total Clicks`)
   */
  clickToConversionRate?: number | null | undefined;
  /**
   * Percentage of leads that convert to paying customers (`Total Conversions ÷ Total Leads`)
   */
  leadToConversionRate?: number | null | undefined;
  /**
   * Return On Ad Spend (ROAS) (`Total Revenue ÷ Total Commissions`)
   */
  returnOnAdSpend?: number | null | undefined;
  /**
   * The partner's website URL (including the https protocol).
   */
  website?: string | null | undefined;
  /**
   * The partner's YouTube channel username (e.g. `johndoe`).
   */
  youtube?: string | null | undefined;
  /**
   * The partner's Twitter username (e.g. `johndoe`).
   */
  twitter?: string | null | undefined;
  /**
   * The partner's LinkedIn username (e.g. `johndoe`).
   */
  linkedin?: string | null | undefined;
  /**
   * The partner's Instagram username (e.g. `johndoe`).
   */
  instagram?: string | null | undefined;
  /**
   * The partner's TikTok username (e.g. `johndoe`).
   */
  tiktok?: string | null | undefined;
};

/** @internal */
export const ListPartnersQueryParamStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListPartnersQueryParamStatus
> = z.nativeEnum(ListPartnersQueryParamStatus);

/** @internal */
export const ListPartnersQueryParamSortBy$outboundSchema: z.ZodNativeEnum<
  typeof ListPartnersQueryParamSortBy
> = z.nativeEnum(ListPartnersQueryParamSortBy);

/** @internal */
export const ListPartnersQueryParamSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof ListPartnersQueryParamSortOrder
> = z.nativeEnum(ListPartnersQueryParamSortOrder);

/** @internal */
export type ListPartnersRequest$Outbound = {
  status?: string | undefined;
  country?: string | undefined;
  sortBy: string;
  sortOrder: string;
  email?: string | undefined;
  tenantId?: string | undefined;
  search?: string | undefined;
  page: number;
  pageSize: number;
};

/** @internal */
export const ListPartnersRequest$outboundSchema: z.ZodType<
  ListPartnersRequest$Outbound,
  z.ZodTypeDef,
  ListPartnersRequest
> = z.object({
  status: ListPartnersQueryParamStatus$outboundSchema.optional(),
  country: z.string().optional(),
  sortBy: ListPartnersQueryParamSortBy$outboundSchema.default(
    "totalSaleAmount",
  ),
  sortOrder: ListPartnersQueryParamSortOrder$outboundSchema.default("desc"),
  email: z.string().optional(),
  tenantId: z.string().optional(),
  search: z.string().optional(),
  page: z.number().default(1),
  pageSize: z.number().default(100),
});

export function listPartnersRequestToJSON(
  listPartnersRequest: ListPartnersRequest,
): string {
  return JSON.stringify(
    ListPartnersRequest$outboundSchema.parse(listPartnersRequest),
  );
}

/** @internal */
export const ListPartnersStatus$inboundSchema: z.ZodNativeEnum<
  typeof ListPartnersStatus
> = z.nativeEnum(ListPartnersStatus);

/** @internal */
export const ListPartnersLinks$inboundSchema: z.ZodType<
  ListPartnersLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  domain: z.string(),
  key: z.string(),
  shortLink: z.string(),
  url: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  conversions: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
});

export function listPartnersLinksFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersLinks' from JSON`,
  );
}

/** @internal */
export const ListPartnersBannedReason$inboundSchema: z.ZodNativeEnum<
  typeof ListPartnersBannedReason
> = z.nativeEnum(ListPartnersBannedReason);

/** @internal */
export const Fields8$inboundSchema: z.ZodType<Fields8, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("phone"),
  });

export function fields8FromJSON(
  jsonString: string,
): SafeParseResult<Fields8, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields8$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields8' from JSON`,
  );
}

/** @internal */
export const Fields7$inboundSchema: z.ZodType<Fields7, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("number"),
  });

export function fields7FromJSON(
  jsonString: string,
): SafeParseResult<Fields7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields7' from JSON`,
  );
}

/** @internal */
export const ListPartnersFieldsPartnersOptions$inboundSchema: z.ZodType<
  ListPartnersFieldsPartnersOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  value: z.string(),
});

export function listPartnersFieldsPartnersOptionsFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFieldsPartnersOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFieldsPartnersOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFieldsPartnersOptions' from JSON`,
  );
}

/** @internal */
export const Fields6$inboundSchema: z.ZodType<Fields6, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("multiSelect"),
    options: z.array(
      z.lazy(() => ListPartnersFieldsPartnersOptions$inboundSchema),
    ),
  });

export function fields6FromJSON(
  jsonString: string,
): SafeParseResult<Fields6, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields6$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields6' from JSON`,
  );
}

/** @internal */
export const Fields5$inboundSchema: z.ZodType<Fields5, z.ZodTypeDef, unknown> =
  z.object({
    key: z.string(),
    label: z.string(),
    required: z.boolean(),
    locked: z.boolean(),
    position: z.number().int(),
    type: z.literal("date"),
  });

export function fields5FromJSON(
  jsonString: string,
): SafeParseResult<Fields5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields5' from JSON`,
  );
}

/** @internal */
export const ListPartnersFields4$inboundSchema: z.ZodType<
  ListPartnersFields4,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  label: z.string(),
  required: z.boolean(),
  locked: z.boolean(),
  position: z.number().int(),
  type: z.literal("country"),
});

export function listPartnersFields4FromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFields4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFields4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFields4' from JSON`,
  );
}

/** @internal */
export const ListPartnersFieldsOptions$inboundSchema: z.ZodType<
  ListPartnersFieldsOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  value: z.string(),
});

export function listPartnersFieldsOptionsFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFieldsOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFieldsOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFieldsOptions' from JSON`,
  );
}

/** @internal */
export const ListPartnersFields3$inboundSchema: z.ZodType<
  ListPartnersFields3,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  label: z.string(),
  required: z.boolean(),
  locked: z.boolean(),
  position: z.number().int(),
  type: z.literal("select"),
  options: z.array(z.lazy(() => ListPartnersFieldsOptions$inboundSchema)),
});

export function listPartnersFields3FromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFields3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFields3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFields3' from JSON`,
  );
}

/** @internal */
export const ListPartnersFieldsPartnersConstraints$inboundSchema: z.ZodType<
  ListPartnersFieldsPartnersConstraints,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxLength: z.number().int().optional(),
});

export function listPartnersFieldsPartnersConstraintsFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFieldsPartnersConstraints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListPartnersFieldsPartnersConstraints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFieldsPartnersConstraints' from JSON`,
  );
}

/** @internal */
export const ListPartnersFields2$inboundSchema: z.ZodType<
  ListPartnersFields2,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  label: z.string(),
  required: z.boolean(),
  locked: z.boolean(),
  position: z.number().int(),
  type: z.literal("textarea"),
  constraints: z.lazy(() => ListPartnersFieldsPartnersConstraints$inboundSchema)
    .optional(),
});

export function listPartnersFields2FromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFields2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFields2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFields2' from JSON`,
  );
}

/** @internal */
export const ListPartnersFieldsConstraints$inboundSchema: z.ZodType<
  ListPartnersFieldsConstraints,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxLength: z.number().int().optional(),
  pattern: z.string().optional(),
});

export function listPartnersFieldsConstraintsFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFieldsConstraints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFieldsConstraints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFieldsConstraints' from JSON`,
  );
}

/** @internal */
export const ListPartnersFields1$inboundSchema: z.ZodType<
  ListPartnersFields1,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  label: z.string(),
  required: z.boolean(),
  locked: z.boolean(),
  position: z.number().int(),
  type: z.literal("text"),
  constraints: z.lazy(() => ListPartnersFieldsConstraints$inboundSchema)
    .optional(),
});

export function listPartnersFields1FromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFields1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFields1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFields1' from JSON`,
  );
}

/** @internal */
export const ListPartnersFields$inboundSchema: z.ZodType<
  ListPartnersFields,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListPartnersFields1$inboundSchema),
  z.lazy(() => ListPartnersFields2$inboundSchema),
  z.lazy(() => ListPartnersFields3$inboundSchema),
  z.lazy(() => ListPartnersFields4$inboundSchema),
  z.lazy(() => Fields5$inboundSchema),
  z.lazy(() => Fields6$inboundSchema),
  z.lazy(() => Fields7$inboundSchema),
  z.lazy(() => Fields8$inboundSchema),
]);

export function listPartnersFieldsFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersFields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersFields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersFields' from JSON`,
  );
}

/** @internal */
export const ListPartnersReferralFormData$inboundSchema: z.ZodType<
  ListPartnersReferralFormData,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.array(
    z.union([
      z.lazy(() => ListPartnersFields1$inboundSchema),
      z.lazy(() => ListPartnersFields2$inboundSchema),
      z.lazy(() => ListPartnersFields3$inboundSchema),
      z.lazy(() => ListPartnersFields4$inboundSchema),
      z.lazy(() => Fields5$inboundSchema),
      z.lazy(() => Fields6$inboundSchema),
      z.lazy(() => Fields7$inboundSchema),
      z.lazy(() => Fields8$inboundSchema),
    ]),
  ),
});

export function listPartnersReferralFormDataFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersReferralFormData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersReferralFormData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersReferralFormData' from JSON`,
  );
}

/** @internal */
export const ListPartnersResponseBody$inboundSchema: z.ZodType<
  ListPartnersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  companyName: z.nullable(z.string()),
  email: z.nullable(z.string()),
  image: z.nullable(z.string()),
  description: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()),
  paypalEmail: z.nullable(z.string()),
  stripeConnectId: z.nullable(z.string()),
  payoutsEnabledAt: z.nullable(z.string()),
  trustedAt: z.nullable(z.string()),
  programId: z.string(),
  groupId: z.nullable(z.string()).optional(),
  partnerId: z.string(),
  tenantId: z.nullable(z.string()),
  createdAt: z.string(),
  status: ListPartnersStatus$inboundSchema,
  links: z.nullable(z.array(z.lazy(() => ListPartnersLinks$inboundSchema))),
  totalCommissions: z.number().default(0),
  clickRewardId: z.nullable(z.string()).optional(),
  leadRewardId: z.nullable(z.string()).optional(),
  saleRewardId: z.nullable(z.string()).optional(),
  discountId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
  bannedAt: z.nullable(z.string()).optional(),
  bannedReason: z.nullable(ListPartnersBannedReason$inboundSchema).optional(),
  referralFormData: z.nullable(
    z.lazy(() => ListPartnersReferralFormData$inboundSchema),
  ).optional(),
  totalClicks: z.number().default(0),
  totalLeads: z.number().default(0),
  totalConversions: z.number().default(0),
  totalSales: z.number().default(0),
  totalSaleAmount: z.number().default(0),
  netRevenue: z.number().default(0),
  earningsPerClick: z.nullable(z.number()).optional(),
  averageLifetimeValue: z.nullable(z.number()).optional(),
  clickToLeadRate: z.nullable(z.number()).optional(),
  clickToConversionRate: z.nullable(z.number()).optional(),
  leadToConversionRate: z.nullable(z.number()).optional(),
  returnOnAdSpend: z.nullable(z.number()).optional(),
  website: z.nullable(z.string()).optional(),
  youtube: z.nullable(z.string()).optional(),
  twitter: z.nullable(z.string()).optional(),
  linkedin: z.nullable(z.string()).optional(),
  instagram: z.nullable(z.string()).optional(),
  tiktok: z.nullable(z.string()).optional(),
});

export function listPartnersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListPartnersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPartnersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPartnersResponseBody' from JSON`,
  );
}
