/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The sort order. The default is `desc`.
 */
export const ListProgramApplicationsQueryParamSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The sort order. The default is `desc`.
 */
export type ListProgramApplicationsQueryParamSortOrder = ClosedEnum<
  typeof ListProgramApplicationsQueryParamSortOrder
>;

/**
 * Filter applications by status. One of `pending`, `approved`, or `rejected`. Defaults to `pending`.
 */
export const QueryParamStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
} as const;
/**
 * Filter applications by status. One of `pending`, `approved`, or `rejected`. Defaults to `pending`.
 */
export type QueryParamStatus = ClosedEnum<typeof QueryParamStatus>;

export type ListProgramApplicationsRequest = {
  /**
   * A filter on the list based on the partner's `country` field.
   */
  country?: string | undefined;
  /**
   * A filter on the list based on the partner's `groupId` field.
   */
  groupId?: string | undefined;
  /**
   * The sort order. The default is `desc`.
   */
  sortOrder?: ListProgramApplicationsQueryParamSortOrder | undefined;
  /**
   * Filter applications by name, email, or company name. Partial matches are supported. An exact partner ID is also matched.
   */
  search?: string | undefined;
  /**
   * Filter applications by status. One of `pending`, `approved`, or `rejected`. Defaults to `pending`.
   */
  status?: QueryParamStatus | undefined;
  /**
   * The page number for pagination. The first page is `1`.
   */
  page?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

/**
 * The status of the partner's enrollment in the program.
 */
export const ListProgramApplicationsStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Invited: "invited",
  Declined: "declined",
  Deactivated: "deactivated",
  Banned: "banned",
  Archived: "archived",
} as const;
/**
 * The status of the partner's enrollment in the program.
 */
export type ListProgramApplicationsStatus = ClosedEnum<
  typeof ListProgramApplicationsStatus
>;

/**
 * The partner's network status on Dub.
 */
export const ListProgramApplicationsNetworkStatus = {
  Draft: "draft",
  Submitted: "submitted",
  Approved: "approved",
  Rejected: "rejected",
  Trusted: "trusted",
} as const;
/**
 * The partner's network status on Dub.
 */
export type ListProgramApplicationsNetworkStatus = ClosedEnum<
  typeof ListProgramApplicationsNetworkStatus
>;

/**
 * The partner's default payout method. Connect: Bank account payouts via Stripe Connect; Stablecoin: USDC payouts directly to a crypto wallet; PayPal: Payouts via PayPal
 */
export const ListProgramApplicationsDefaultPayoutMethod = {
  Connect: "connect",
  Stablecoin: "stablecoin",
  Paypal: "paypal",
  Tremendous: "tremendous",
} as const;
/**
 * The partner's default payout method. Connect: Bank account payouts via Stripe Connect; Stablecoin: USDC payouts directly to a crypto wallet; PayPal: Payouts via PayPal
 */
export type ListProgramApplicationsDefaultPayoutMethod = ClosedEnum<
  typeof ListProgramApplicationsDefaultPayoutMethod
>;

export const ListProgramApplicationsType = {
  Website: "website",
  Youtube: "youtube",
  Twitter: "twitter",
  Linkedin: "linkedin",
  Instagram: "instagram",
  Tiktok: "tiktok",
} as const;
export type ListProgramApplicationsType = ClosedEnum<
  typeof ListProgramApplicationsType
>;

export type Platforms = {
  type: ListProgramApplicationsType;
  identifier: string;
  verifiedAt: string | null;
};

export type ListProgramApplicationsPartner = {
  /**
   * The partner's unique ID on Dub.
   */
  id: string;
  /**
   * The partner's full legal name.
   */
  name: string;
  /**
   * If the partner profile type is a company, this is the partner's legal company name.
   */
  companyName: string | null;
  /**
   * The partner's email address. Should be a unique value across Dub.
   */
  email: string | null;
  /**
   * The partner's avatar image.
   */
  image: string | null;
  /**
   * A brief description of the partner and their background.
   */
  description?: string | null | undefined;
  /**
   * The partner's country (required for tax purposes).
   */
  country: string | null;
  /**
   * The partner's group ID on Dub.
   */
  groupId?: string | null | undefined;
  /**
   * The status of the partner's enrollment in the program.
   */
  status: ListProgramApplicationsStatus;
  /**
   * The partner's website URL (including the https protocol).
   */
  website?: string | null | undefined;
  /**
   * The partner's YouTube channel username (e.g. `johndoe`).
   */
  youtube?: string | null | undefined;
  /**
   * The partner's Twitter username (e.g. `johndoe`).
   */
  twitter?: string | null | undefined;
  /**
   * The partner's LinkedIn username (e.g. `johndoe`).
   */
  linkedin?: string | null | undefined;
  /**
   * The partner's Instagram username (e.g. `johndoe`).
   */
  instagram?: string | null | undefined;
  /**
   * The partner's TikTok username (e.g. `johndoe`).
   */
  tiktok?: string | null | undefined;
  /**
   * The partner's network status on Dub.
   */
  networkStatus: ListProgramApplicationsNetworkStatus;
  /**
   * The partner's default payout method. Connect: Bank account payouts via Stripe Connect; Stablecoin: USDC payouts directly to a crypto wallet; PayPal: Payouts via PayPal
   */
  defaultPayoutMethod: ListProgramApplicationsDefaultPayoutMethod | null;
  /**
   * The date when the partner enabled payouts.
   */
  payoutsEnabledAt: string | null;
  /**
   * The partner's website and social profiles, including when each was verified.
   */
  platforms?: Array<Platforms> | null | undefined;
};

export type ApplicationFormData = {
  label: string;
  value: string | null;
};

export type ListProgramApplicationsResponseBody = {
  id: string;
  createdAt: string;
  partner: ListProgramApplicationsPartner;
  applicationFormData: Array<ApplicationFormData> | null;
};

/** @internal */
export const ListProgramApplicationsQueryParamSortOrder$outboundSchema:
  z.ZodNativeEnum<typeof ListProgramApplicationsQueryParamSortOrder> = z
    .nativeEnum(ListProgramApplicationsQueryParamSortOrder);

/** @internal */
export const QueryParamStatus$outboundSchema: z.ZodNativeEnum<
  typeof QueryParamStatus
> = z.nativeEnum(QueryParamStatus);

/** @internal */
export type ListProgramApplicationsRequest$Outbound = {
  country?: string | undefined;
  groupId?: string | undefined;
  sortOrder: string;
  search?: string | undefined;
  status: string;
  page?: number | undefined;
  pageSize: number;
};

/** @internal */
export const ListProgramApplicationsRequest$outboundSchema: z.ZodType<
  ListProgramApplicationsRequest$Outbound,
  z.ZodTypeDef,
  ListProgramApplicationsRequest
> = z.object({
  country: z.string().optional(),
  groupId: z.string().optional(),
  sortOrder: ListProgramApplicationsQueryParamSortOrder$outboundSchema.default(
    "desc",
  ),
  search: z.string().optional(),
  status: QueryParamStatus$outboundSchema.default("pending"),
  page: z.number().int().optional(),
  pageSize: z.number().int().default(100),
});

export function listProgramApplicationsRequestToJSON(
  listProgramApplicationsRequest: ListProgramApplicationsRequest,
): string {
  return JSON.stringify(
    ListProgramApplicationsRequest$outboundSchema.parse(
      listProgramApplicationsRequest,
    ),
  );
}

/** @internal */
export const ListProgramApplicationsStatus$inboundSchema: z.ZodNativeEnum<
  typeof ListProgramApplicationsStatus
> = z.nativeEnum(ListProgramApplicationsStatus);

/** @internal */
export const ListProgramApplicationsNetworkStatus$inboundSchema:
  z.ZodNativeEnum<typeof ListProgramApplicationsNetworkStatus> = z.nativeEnum(
    ListProgramApplicationsNetworkStatus,
  );

/** @internal */
export const ListProgramApplicationsDefaultPayoutMethod$inboundSchema:
  z.ZodNativeEnum<typeof ListProgramApplicationsDefaultPayoutMethod> = z
    .nativeEnum(ListProgramApplicationsDefaultPayoutMethod);

/** @internal */
export const ListProgramApplicationsType$inboundSchema: z.ZodNativeEnum<
  typeof ListProgramApplicationsType
> = z.nativeEnum(ListProgramApplicationsType);

/** @internal */
export const Platforms$inboundSchema: z.ZodType<
  Platforms,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: ListProgramApplicationsType$inboundSchema,
  identifier: z.string(),
  verifiedAt: z.nullable(z.string()),
});

export function platformsFromJSON(
  jsonString: string,
): SafeParseResult<Platforms, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Platforms$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Platforms' from JSON`,
  );
}

/** @internal */
export const ListProgramApplicationsPartner$inboundSchema: z.ZodType<
  ListProgramApplicationsPartner,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  companyName: z.nullable(z.string()),
  email: z.nullable(z.string()),
  image: z.nullable(z.string()),
  description: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()),
  groupId: z.nullable(z.string()).optional(),
  status: ListProgramApplicationsStatus$inboundSchema,
  website: z.nullable(z.string()).optional(),
  youtube: z.nullable(z.string()).optional(),
  twitter: z.nullable(z.string()).optional(),
  linkedin: z.nullable(z.string()).optional(),
  instagram: z.nullable(z.string()).optional(),
  tiktok: z.nullable(z.string()).optional(),
  networkStatus: ListProgramApplicationsNetworkStatus$inboundSchema,
  defaultPayoutMethod: z.nullable(
    ListProgramApplicationsDefaultPayoutMethod$inboundSchema,
  ),
  payoutsEnabledAt: z.nullable(z.string()),
  platforms: z.nullable(z.array(z.lazy(() => Platforms$inboundSchema)))
    .optional(),
});

export function listProgramApplicationsPartnerFromJSON(
  jsonString: string,
): SafeParseResult<ListProgramApplicationsPartner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProgramApplicationsPartner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProgramApplicationsPartner' from JSON`,
  );
}

/** @internal */
export const ApplicationFormData$inboundSchema: z.ZodType<
  ApplicationFormData,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  value: z.nullable(z.string()),
});

export function applicationFormDataFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationFormData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationFormData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationFormData' from JSON`,
  );
}

/** @internal */
export const ListProgramApplicationsResponseBody$inboundSchema: z.ZodType<
  ListProgramApplicationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  createdAt: z.string(),
  partner: z.lazy(() => ListProgramApplicationsPartner$inboundSchema),
  applicationFormData: z.nullable(
    z.array(z.lazy(() => ApplicationFormData$inboundSchema)),
  ),
});

export function listProgramApplicationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListProgramApplicationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListProgramApplicationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProgramApplicationsResponseBody' from JSON`,
  );
}
