// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type AnalyticsTimeseries struct {
	// The starting timestamp of the interval
	Start string `json:"start"`
	// The number of clicks in the interval
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads in the interval
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales in the interval
	Sales *float64 `default:"0" json:"sales"`
	// The total amount of sales in the interval, in cents
	SaleAmount *float64 `default:"0" json:"saleAmount"`
}

func (a AnalyticsTimeseries) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsTimeseries) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AnalyticsTimeseries) GetStart() string {
	if o == nil {
		return ""
	}
	return o.Start
}

func (o *AnalyticsTimeseries) GetClicks() *float64 {
	if o == nil {
		return nil
	}
	return o.Clicks
}

func (o *AnalyticsTimeseries) GetLeads() *float64 {
	if o == nil {
		return nil
	}
	return o.Leads
}

func (o *AnalyticsTimeseries) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *AnalyticsTimeseries) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}
