// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type LinkClickedEventEvent string

const (
	LinkClickedEventEventLinkClicked LinkClickedEventEvent = "link.clicked"
)

func (e LinkClickedEventEvent) ToPointer() *LinkClickedEventEvent {
	return &e
}
func (e *LinkClickedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link.clicked":
		*e = LinkClickedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LinkClickedEventEvent: %v", v)
	}
}

type LinkClickedEventClick struct {
	ID         string `json:"id"`
	Timestamp  string `json:"timestamp"`
	URL        string `json:"url"`
	Country    string `json:"country"`
	City       string `json:"city"`
	Region     string `json:"region"`
	Continent  string `json:"continent"`
	Device     string `json:"device"`
	Browser    string `json:"browser"`
	Os         string `json:"os"`
	Referer    string `json:"referer"`
	RefererURL string `json:"refererUrl"`
	Qr         bool   `json:"qr"`
	IP         string `json:"ip"`
}

func (o *LinkClickedEventClick) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LinkClickedEventClick) GetTimestamp() string {
	if o == nil {
		return ""
	}
	return o.Timestamp
}

func (o *LinkClickedEventClick) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LinkClickedEventClick) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *LinkClickedEventClick) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *LinkClickedEventClick) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *LinkClickedEventClick) GetContinent() string {
	if o == nil {
		return ""
	}
	return o.Continent
}

func (o *LinkClickedEventClick) GetDevice() string {
	if o == nil {
		return ""
	}
	return o.Device
}

func (o *LinkClickedEventClick) GetBrowser() string {
	if o == nil {
		return ""
	}
	return o.Browser
}

func (o *LinkClickedEventClick) GetOs() string {
	if o == nil {
		return ""
	}
	return o.Os
}

func (o *LinkClickedEventClick) GetReferer() string {
	if o == nil {
		return ""
	}
	return o.Referer
}

func (o *LinkClickedEventClick) GetRefererURL() string {
	if o == nil {
		return ""
	}
	return o.RefererURL
}

func (o *LinkClickedEventClick) GetQr() bool {
	if o == nil {
		return false
	}
	return o.Qr
}

func (o *LinkClickedEventClick) GetIP() string {
	if o == nil {
		return ""
	}
	return o.IP
}

// LinkClickedEventGeo - Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
type LinkClickedEventGeo struct {
	Af *string `json:"AF,omitempty"`
	Al *string `json:"AL,omitempty"`
	Dz *string `json:"DZ,omitempty"`
	As *string `json:"AS,omitempty"`
	Ad *string `json:"AD,omitempty"`
	Ao *string `json:"AO,omitempty"`
	Ai *string `json:"AI,omitempty"`
	Aq *string `json:"AQ,omitempty"`
	Ag *string `json:"AG,omitempty"`
	Ar *string `json:"AR,omitempty"`
	Am *string `json:"AM,omitempty"`
	Aw *string `json:"AW,omitempty"`
	Au *string `json:"AU,omitempty"`
	At *string `json:"AT,omitempty"`
	Az *string `json:"AZ,omitempty"`
	Bs *string `json:"BS,omitempty"`
	Bh *string `json:"BH,omitempty"`
	Bd *string `json:"BD,omitempty"`
	Bb *string `json:"BB,omitempty"`
	By *string `json:"BY,omitempty"`
	Be *string `json:"BE,omitempty"`
	Bz *string `json:"BZ,omitempty"`
	Bj *string `json:"BJ,omitempty"`
	Bm *string `json:"BM,omitempty"`
	Bt *string `json:"BT,omitempty"`
	Bo *string `json:"BO,omitempty"`
	Ba *string `json:"BA,omitempty"`
	Bw *string `json:"BW,omitempty"`
	Bv *string `json:"BV,omitempty"`
	Br *string `json:"BR,omitempty"`
	Io *string `json:"IO,omitempty"`
	Bn *string `json:"BN,omitempty"`
	Bg *string `json:"BG,omitempty"`
	Bf *string `json:"BF,omitempty"`
	Bi *string `json:"BI,omitempty"`
	Kh *string `json:"KH,omitempty"`
	Cm *string `json:"CM,omitempty"`
	Ca *string `json:"CA,omitempty"`
	Cv *string `json:"CV,omitempty"`
	Ky *string `json:"KY,omitempty"`
	Cf *string `json:"CF,omitempty"`
	Td *string `json:"TD,omitempty"`
	Cl *string `json:"CL,omitempty"`
	Cn *string `json:"CN,omitempty"`
	Cx *string `json:"CX,omitempty"`
	Cc *string `json:"CC,omitempty"`
	Co *string `json:"CO,omitempty"`
	Km *string `json:"KM,omitempty"`
	Cg *string `json:"CG,omitempty"`
	Cd *string `json:"CD,omitempty"`
	Ck *string `json:"CK,omitempty"`
	Cr *string `json:"CR,omitempty"`
	Ci *string `json:"CI,omitempty"`
	Hr *string `json:"HR,omitempty"`
	Cu *string `json:"CU,omitempty"`
	Cy *string `json:"CY,omitempty"`
	Cz *string `json:"CZ,omitempty"`
	Dk *string `json:"DK,omitempty"`
	Dj *string `json:"DJ,omitempty"`
	Dm *string `json:"DM,omitempty"`
	Do *string `json:"DO,omitempty"`
	Ec *string `json:"EC,omitempty"`
	Eg *string `json:"EG,omitempty"`
	Sv *string `json:"SV,omitempty"`
	Gq *string `json:"GQ,omitempty"`
	Er *string `json:"ER,omitempty"`
	Ee *string `json:"EE,omitempty"`
	Et *string `json:"ET,omitempty"`
	Fk *string `json:"FK,omitempty"`
	Fo *string `json:"FO,omitempty"`
	Fj *string `json:"FJ,omitempty"`
	Fi *string `json:"FI,omitempty"`
	Fr *string `json:"FR,omitempty"`
	Gf *string `json:"GF,omitempty"`
	Pf *string `json:"PF,omitempty"`
	Tf *string `json:"TF,omitempty"`
	Ga *string `json:"GA,omitempty"`
	Gm *string `json:"GM,omitempty"`
	Ge *string `json:"GE,omitempty"`
	De *string `json:"DE,omitempty"`
	Gh *string `json:"GH,omitempty"`
	Gi *string `json:"GI,omitempty"`
	Gr *string `json:"GR,omitempty"`
	Gl *string `json:"GL,omitempty"`
	Gd *string `json:"GD,omitempty"`
	Gp *string `json:"GP,omitempty"`
	Gu *string `json:"GU,omitempty"`
	Gt *string `json:"GT,omitempty"`
	Gn *string `json:"GN,omitempty"`
	Gw *string `json:"GW,omitempty"`
	Gy *string `json:"GY,omitempty"`
	Ht *string `json:"HT,omitempty"`
	Hm *string `json:"HM,omitempty"`
	Va *string `json:"VA,omitempty"`
	Hn *string `json:"HN,omitempty"`
	Hk *string `json:"HK,omitempty"`
	Hu *string `json:"HU,omitempty"`
	Is *string `json:"IS,omitempty"`
	In *string `json:"IN,omitempty"`
	ID *string `json:"ID,omitempty"`
	Ir *string `json:"IR,omitempty"`
	Iq *string `json:"IQ,omitempty"`
	Ie *string `json:"IE,omitempty"`
	Il *string `json:"IL,omitempty"`
	It *string `json:"IT,omitempty"`
	Jm *string `json:"JM,omitempty"`
	Jp *string `json:"JP,omitempty"`
	Jo *string `json:"JO,omitempty"`
	Kz *string `json:"KZ,omitempty"`
	Ke *string `json:"KE,omitempty"`
	Ki *string `json:"KI,omitempty"`
	Kp *string `json:"KP,omitempty"`
	Kr *string `json:"KR,omitempty"`
	Kw *string `json:"KW,omitempty"`
	Kg *string `json:"KG,omitempty"`
	La *string `json:"LA,omitempty"`
	Lv *string `json:"LV,omitempty"`
	Lb *string `json:"LB,omitempty"`
	Ls *string `json:"LS,omitempty"`
	Lr *string `json:"LR,omitempty"`
	Ly *string `json:"LY,omitempty"`
	Li *string `json:"LI,omitempty"`
	Lt *string `json:"LT,omitempty"`
	Lu *string `json:"LU,omitempty"`
	Mo *string `json:"MO,omitempty"`
	Mg *string `json:"MG,omitempty"`
	Mw *string `json:"MW,omitempty"`
	My *string `json:"MY,omitempty"`
	Mv *string `json:"MV,omitempty"`
	Ml *string `json:"ML,omitempty"`
	Mt *string `json:"MT,omitempty"`
	Mh *string `json:"MH,omitempty"`
	Mq *string `json:"MQ,omitempty"`
	Mr *string `json:"MR,omitempty"`
	Mu *string `json:"MU,omitempty"`
	Yt *string `json:"YT,omitempty"`
	Mx *string `json:"MX,omitempty"`
	Fm *string `json:"FM,omitempty"`
	Md *string `json:"MD,omitempty"`
	Mc *string `json:"MC,omitempty"`
	Mn *string `json:"MN,omitempty"`
	Ms *string `json:"MS,omitempty"`
	Ma *string `json:"MA,omitempty"`
	Mz *string `json:"MZ,omitempty"`
	Mm *string `json:"MM,omitempty"`
	Na *string `json:"NA,omitempty"`
	Nr *string `json:"NR,omitempty"`
	Np *string `json:"NP,omitempty"`
	Nl *string `json:"NL,omitempty"`
	Nc *string `json:"NC,omitempty"`
	Nz *string `json:"NZ,omitempty"`
	Ni *string `json:"NI,omitempty"`
	Ne *string `json:"NE,omitempty"`
	Ng *string `json:"NG,omitempty"`
	Nu *string `json:"NU,omitempty"`
	Nf *string `json:"NF,omitempty"`
	Mk *string `json:"MK,omitempty"`
	Mp *string `json:"MP,omitempty"`
	No *string `json:"NO,omitempty"`
	Om *string `json:"OM,omitempty"`
	Pk *string `json:"PK,omitempty"`
	Pw *string `json:"PW,omitempty"`
	Ps *string `json:"PS,omitempty"`
	Pa *string `json:"PA,omitempty"`
	Pg *string `json:"PG,omitempty"`
	Py *string `json:"PY,omitempty"`
	Pe *string `json:"PE,omitempty"`
	Ph *string `json:"PH,omitempty"`
	Pn *string `json:"PN,omitempty"`
	Pl *string `json:"PL,omitempty"`
	Pt *string `json:"PT,omitempty"`
	Pr *string `json:"PR,omitempty"`
	Qa *string `json:"QA,omitempty"`
	Re *string `json:"RE,omitempty"`
	Ro *string `json:"RO,omitempty"`
	Ru *string `json:"RU,omitempty"`
	Rw *string `json:"RW,omitempty"`
	Sh *string `json:"SH,omitempty"`
	Kn *string `json:"KN,omitempty"`
	Lc *string `json:"LC,omitempty"`
	Pm *string `json:"PM,omitempty"`
	Vc *string `json:"VC,omitempty"`
	Ws *string `json:"WS,omitempty"`
	Sm *string `json:"SM,omitempty"`
	St *string `json:"ST,omitempty"`
	Sa *string `json:"SA,omitempty"`
	Sn *string `json:"SN,omitempty"`
	Sc *string `json:"SC,omitempty"`
	Sl *string `json:"SL,omitempty"`
	Sg *string `json:"SG,omitempty"`
	Sk *string `json:"SK,omitempty"`
	Si *string `json:"SI,omitempty"`
	Sb *string `json:"SB,omitempty"`
	So *string `json:"SO,omitempty"`
	Za *string `json:"ZA,omitempty"`
	Gs *string `json:"GS,omitempty"`
	Es *string `json:"ES,omitempty"`
	Lk *string `json:"LK,omitempty"`
	Sd *string `json:"SD,omitempty"`
	Sr *string `json:"SR,omitempty"`
	Sj *string `json:"SJ,omitempty"`
	Sz *string `json:"SZ,omitempty"`
	Se *string `json:"SE,omitempty"`
	Ch *string `json:"CH,omitempty"`
	Sy *string `json:"SY,omitempty"`
	Tw *string `json:"TW,omitempty"`
	Tj *string `json:"TJ,omitempty"`
	Tz *string `json:"TZ,omitempty"`
	Th *string `json:"TH,omitempty"`
	Tl *string `json:"TL,omitempty"`
	Tg *string `json:"TG,omitempty"`
	Tk *string `json:"TK,omitempty"`
	To *string `json:"TO,omitempty"`
	Tt *string `json:"TT,omitempty"`
	Tn *string `json:"TN,omitempty"`
	Tr *string `json:"TR,omitempty"`
	Tm *string `json:"TM,omitempty"`
	Tc *string `json:"TC,omitempty"`
	Tv *string `json:"TV,omitempty"`
	Ug *string `json:"UG,omitempty"`
	Ua *string `json:"UA,omitempty"`
	Ae *string `json:"AE,omitempty"`
	Gb *string `json:"GB,omitempty"`
	Us *string `json:"US,omitempty"`
	Um *string `json:"UM,omitempty"`
	Uy *string `json:"UY,omitempty"`
	Uz *string `json:"UZ,omitempty"`
	Vu *string `json:"VU,omitempty"`
	Ve *string `json:"VE,omitempty"`
	Vn *string `json:"VN,omitempty"`
	Vg *string `json:"VG,omitempty"`
	Vi *string `json:"VI,omitempty"`
	Wf *string `json:"WF,omitempty"`
	Eh *string `json:"EH,omitempty"`
	Ye *string `json:"YE,omitempty"`
	Zm *string `json:"ZM,omitempty"`
	Zw *string `json:"ZW,omitempty"`
	Ax *string `json:"AX,omitempty"`
	Bq *string `json:"BQ,omitempty"`
	Cw *string `json:"CW,omitempty"`
	Gg *string `json:"GG,omitempty"`
	Im *string `json:"IM,omitempty"`
	Je *string `json:"JE,omitempty"`
	Me *string `json:"ME,omitempty"`
	Bl *string `json:"BL,omitempty"`
	Mf *string `json:"MF,omitempty"`
	Rs *string `json:"RS,omitempty"`
	Sx *string `json:"SX,omitempty"`
	Ss *string `json:"SS,omitempty"`
	Xk *string `json:"XK,omitempty"`
}

func (o *LinkClickedEventGeo) GetAf() *string {
	if o == nil {
		return nil
	}
	return o.Af
}

func (o *LinkClickedEventGeo) GetAl() *string {
	if o == nil {
		return nil
	}
	return o.Al
}

func (o *LinkClickedEventGeo) GetDz() *string {
	if o == nil {
		return nil
	}
	return o.Dz
}

func (o *LinkClickedEventGeo) GetAs() *string {
	if o == nil {
		return nil
	}
	return o.As
}

func (o *LinkClickedEventGeo) GetAd() *string {
	if o == nil {
		return nil
	}
	return o.Ad
}

func (o *LinkClickedEventGeo) GetAo() *string {
	if o == nil {
		return nil
	}
	return o.Ao
}

func (o *LinkClickedEventGeo) GetAi() *string {
	if o == nil {
		return nil
	}
	return o.Ai
}

func (o *LinkClickedEventGeo) GetAq() *string {
	if o == nil {
		return nil
	}
	return o.Aq
}

func (o *LinkClickedEventGeo) GetAg() *string {
	if o == nil {
		return nil
	}
	return o.Ag
}

func (o *LinkClickedEventGeo) GetAr() *string {
	if o == nil {
		return nil
	}
	return o.Ar
}

func (o *LinkClickedEventGeo) GetAm() *string {
	if o == nil {
		return nil
	}
	return o.Am
}

func (o *LinkClickedEventGeo) GetAw() *string {
	if o == nil {
		return nil
	}
	return o.Aw
}

func (o *LinkClickedEventGeo) GetAu() *string {
	if o == nil {
		return nil
	}
	return o.Au
}

func (o *LinkClickedEventGeo) GetAt() *string {
	if o == nil {
		return nil
	}
	return o.At
}

func (o *LinkClickedEventGeo) GetAz() *string {
	if o == nil {
		return nil
	}
	return o.Az
}

func (o *LinkClickedEventGeo) GetBs() *string {
	if o == nil {
		return nil
	}
	return o.Bs
}

func (o *LinkClickedEventGeo) GetBh() *string {
	if o == nil {
		return nil
	}
	return o.Bh
}

func (o *LinkClickedEventGeo) GetBd() *string {
	if o == nil {
		return nil
	}
	return o.Bd
}

func (o *LinkClickedEventGeo) GetBb() *string {
	if o == nil {
		return nil
	}
	return o.Bb
}

func (o *LinkClickedEventGeo) GetBy() *string {
	if o == nil {
		return nil
	}
	return o.By
}

func (o *LinkClickedEventGeo) GetBe() *string {
	if o == nil {
		return nil
	}
	return o.Be
}

func (o *LinkClickedEventGeo) GetBz() *string {
	if o == nil {
		return nil
	}
	return o.Bz
}

func (o *LinkClickedEventGeo) GetBj() *string {
	if o == nil {
		return nil
	}
	return o.Bj
}

func (o *LinkClickedEventGeo) GetBm() *string {
	if o == nil {
		return nil
	}
	return o.Bm
}

func (o *LinkClickedEventGeo) GetBt() *string {
	if o == nil {
		return nil
	}
	return o.Bt
}

func (o *LinkClickedEventGeo) GetBo() *string {
	if o == nil {
		return nil
	}
	return o.Bo
}

func (o *LinkClickedEventGeo) GetBa() *string {
	if o == nil {
		return nil
	}
	return o.Ba
}

func (o *LinkClickedEventGeo) GetBw() *string {
	if o == nil {
		return nil
	}
	return o.Bw
}

func (o *LinkClickedEventGeo) GetBv() *string {
	if o == nil {
		return nil
	}
	return o.Bv
}

func (o *LinkClickedEventGeo) GetBr() *string {
	if o == nil {
		return nil
	}
	return o.Br
}

func (o *LinkClickedEventGeo) GetIo() *string {
	if o == nil {
		return nil
	}
	return o.Io
}

func (o *LinkClickedEventGeo) GetBn() *string {
	if o == nil {
		return nil
	}
	return o.Bn
}

func (o *LinkClickedEventGeo) GetBg() *string {
	if o == nil {
		return nil
	}
	return o.Bg
}

func (o *LinkClickedEventGeo) GetBf() *string {
	if o == nil {
		return nil
	}
	return o.Bf
}

func (o *LinkClickedEventGeo) GetBi() *string {
	if o == nil {
		return nil
	}
	return o.Bi
}

func (o *LinkClickedEventGeo) GetKh() *string {
	if o == nil {
		return nil
	}
	return o.Kh
}

func (o *LinkClickedEventGeo) GetCm() *string {
	if o == nil {
		return nil
	}
	return o.Cm
}

func (o *LinkClickedEventGeo) GetCa() *string {
	if o == nil {
		return nil
	}
	return o.Ca
}

func (o *LinkClickedEventGeo) GetCv() *string {
	if o == nil {
		return nil
	}
	return o.Cv
}

func (o *LinkClickedEventGeo) GetKy() *string {
	if o == nil {
		return nil
	}
	return o.Ky
}

func (o *LinkClickedEventGeo) GetCf() *string {
	if o == nil {
		return nil
	}
	return o.Cf
}

func (o *LinkClickedEventGeo) GetTd() *string {
	if o == nil {
		return nil
	}
	return o.Td
}

func (o *LinkClickedEventGeo) GetCl() *string {
	if o == nil {
		return nil
	}
	return o.Cl
}

func (o *LinkClickedEventGeo) GetCn() *string {
	if o == nil {
		return nil
	}
	return o.Cn
}

func (o *LinkClickedEventGeo) GetCx() *string {
	if o == nil {
		return nil
	}
	return o.Cx
}

func (o *LinkClickedEventGeo) GetCc() *string {
	if o == nil {
		return nil
	}
	return o.Cc
}

func (o *LinkClickedEventGeo) GetCo() *string {
	if o == nil {
		return nil
	}
	return o.Co
}

func (o *LinkClickedEventGeo) GetKm() *string {
	if o == nil {
		return nil
	}
	return o.Km
}

func (o *LinkClickedEventGeo) GetCg() *string {
	if o == nil {
		return nil
	}
	return o.Cg
}

func (o *LinkClickedEventGeo) GetCd() *string {
	if o == nil {
		return nil
	}
	return o.Cd
}

func (o *LinkClickedEventGeo) GetCk() *string {
	if o == nil {
		return nil
	}
	return o.Ck
}

func (o *LinkClickedEventGeo) GetCr() *string {
	if o == nil {
		return nil
	}
	return o.Cr
}

func (o *LinkClickedEventGeo) GetCi() *string {
	if o == nil {
		return nil
	}
	return o.Ci
}

func (o *LinkClickedEventGeo) GetHr() *string {
	if o == nil {
		return nil
	}
	return o.Hr
}

func (o *LinkClickedEventGeo) GetCu() *string {
	if o == nil {
		return nil
	}
	return o.Cu
}

func (o *LinkClickedEventGeo) GetCy() *string {
	if o == nil {
		return nil
	}
	return o.Cy
}

func (o *LinkClickedEventGeo) GetCz() *string {
	if o == nil {
		return nil
	}
	return o.Cz
}

func (o *LinkClickedEventGeo) GetDk() *string {
	if o == nil {
		return nil
	}
	return o.Dk
}

func (o *LinkClickedEventGeo) GetDj() *string {
	if o == nil {
		return nil
	}
	return o.Dj
}

func (o *LinkClickedEventGeo) GetDm() *string {
	if o == nil {
		return nil
	}
	return o.Dm
}

func (o *LinkClickedEventGeo) GetDo() *string {
	if o == nil {
		return nil
	}
	return o.Do
}

func (o *LinkClickedEventGeo) GetEc() *string {
	if o == nil {
		return nil
	}
	return o.Ec
}

func (o *LinkClickedEventGeo) GetEg() *string {
	if o == nil {
		return nil
	}
	return o.Eg
}

func (o *LinkClickedEventGeo) GetSv() *string {
	if o == nil {
		return nil
	}
	return o.Sv
}

func (o *LinkClickedEventGeo) GetGq() *string {
	if o == nil {
		return nil
	}
	return o.Gq
}

func (o *LinkClickedEventGeo) GetEr() *string {
	if o == nil {
		return nil
	}
	return o.Er
}

func (o *LinkClickedEventGeo) GetEe() *string {
	if o == nil {
		return nil
	}
	return o.Ee
}

func (o *LinkClickedEventGeo) GetEt() *string {
	if o == nil {
		return nil
	}
	return o.Et
}

func (o *LinkClickedEventGeo) GetFk() *string {
	if o == nil {
		return nil
	}
	return o.Fk
}

func (o *LinkClickedEventGeo) GetFo() *string {
	if o == nil {
		return nil
	}
	return o.Fo
}

func (o *LinkClickedEventGeo) GetFj() *string {
	if o == nil {
		return nil
	}
	return o.Fj
}

func (o *LinkClickedEventGeo) GetFi() *string {
	if o == nil {
		return nil
	}
	return o.Fi
}

func (o *LinkClickedEventGeo) GetFr() *string {
	if o == nil {
		return nil
	}
	return o.Fr
}

func (o *LinkClickedEventGeo) GetGf() *string {
	if o == nil {
		return nil
	}
	return o.Gf
}

func (o *LinkClickedEventGeo) GetPf() *string {
	if o == nil {
		return nil
	}
	return o.Pf
}

func (o *LinkClickedEventGeo) GetTf() *string {
	if o == nil {
		return nil
	}
	return o.Tf
}

func (o *LinkClickedEventGeo) GetGa() *string {
	if o == nil {
		return nil
	}
	return o.Ga
}

func (o *LinkClickedEventGeo) GetGm() *string {
	if o == nil {
		return nil
	}
	return o.Gm
}

func (o *LinkClickedEventGeo) GetGe() *string {
	if o == nil {
		return nil
	}
	return o.Ge
}

func (o *LinkClickedEventGeo) GetDe() *string {
	if o == nil {
		return nil
	}
	return o.De
}

func (o *LinkClickedEventGeo) GetGh() *string {
	if o == nil {
		return nil
	}
	return o.Gh
}

func (o *LinkClickedEventGeo) GetGi() *string {
	if o == nil {
		return nil
	}
	return o.Gi
}

func (o *LinkClickedEventGeo) GetGr() *string {
	if o == nil {
		return nil
	}
	return o.Gr
}

func (o *LinkClickedEventGeo) GetGl() *string {
	if o == nil {
		return nil
	}
	return o.Gl
}

func (o *LinkClickedEventGeo) GetGd() *string {
	if o == nil {
		return nil
	}
	return o.Gd
}

func (o *LinkClickedEventGeo) GetGp() *string {
	if o == nil {
		return nil
	}
	return o.Gp
}

func (o *LinkClickedEventGeo) GetGu() *string {
	if o == nil {
		return nil
	}
	return o.Gu
}

func (o *LinkClickedEventGeo) GetGt() *string {
	if o == nil {
		return nil
	}
	return o.Gt
}

func (o *LinkClickedEventGeo) GetGn() *string {
	if o == nil {
		return nil
	}
	return o.Gn
}

func (o *LinkClickedEventGeo) GetGw() *string {
	if o == nil {
		return nil
	}
	return o.Gw
}

func (o *LinkClickedEventGeo) GetGy() *string {
	if o == nil {
		return nil
	}
	return o.Gy
}

func (o *LinkClickedEventGeo) GetHt() *string {
	if o == nil {
		return nil
	}
	return o.Ht
}

func (o *LinkClickedEventGeo) GetHm() *string {
	if o == nil {
		return nil
	}
	return o.Hm
}

func (o *LinkClickedEventGeo) GetVa() *string {
	if o == nil {
		return nil
	}
	return o.Va
}

func (o *LinkClickedEventGeo) GetHn() *string {
	if o == nil {
		return nil
	}
	return o.Hn
}

func (o *LinkClickedEventGeo) GetHk() *string {
	if o == nil {
		return nil
	}
	return o.Hk
}

func (o *LinkClickedEventGeo) GetHu() *string {
	if o == nil {
		return nil
	}
	return o.Hu
}

func (o *LinkClickedEventGeo) GetIs() *string {
	if o == nil {
		return nil
	}
	return o.Is
}

func (o *LinkClickedEventGeo) GetIn() *string {
	if o == nil {
		return nil
	}
	return o.In
}

func (o *LinkClickedEventGeo) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LinkClickedEventGeo) GetIr() *string {
	if o == nil {
		return nil
	}
	return o.Ir
}

func (o *LinkClickedEventGeo) GetIq() *string {
	if o == nil {
		return nil
	}
	return o.Iq
}

func (o *LinkClickedEventGeo) GetIe() *string {
	if o == nil {
		return nil
	}
	return o.Ie
}

func (o *LinkClickedEventGeo) GetIl() *string {
	if o == nil {
		return nil
	}
	return o.Il
}

func (o *LinkClickedEventGeo) GetIt() *string {
	if o == nil {
		return nil
	}
	return o.It
}

func (o *LinkClickedEventGeo) GetJm() *string {
	if o == nil {
		return nil
	}
	return o.Jm
}

func (o *LinkClickedEventGeo) GetJp() *string {
	if o == nil {
		return nil
	}
	return o.Jp
}

func (o *LinkClickedEventGeo) GetJo() *string {
	if o == nil {
		return nil
	}
	return o.Jo
}

func (o *LinkClickedEventGeo) GetKz() *string {
	if o == nil {
		return nil
	}
	return o.Kz
}

func (o *LinkClickedEventGeo) GetKe() *string {
	if o == nil {
		return nil
	}
	return o.Ke
}

func (o *LinkClickedEventGeo) GetKi() *string {
	if o == nil {
		return nil
	}
	return o.Ki
}

func (o *LinkClickedEventGeo) GetKp() *string {
	if o == nil {
		return nil
	}
	return o.Kp
}

func (o *LinkClickedEventGeo) GetKr() *string {
	if o == nil {
		return nil
	}
	return o.Kr
}

func (o *LinkClickedEventGeo) GetKw() *string {
	if o == nil {
		return nil
	}
	return o.Kw
}

func (o *LinkClickedEventGeo) GetKg() *string {
	if o == nil {
		return nil
	}
	return o.Kg
}

func (o *LinkClickedEventGeo) GetLa() *string {
	if o == nil {
		return nil
	}
	return o.La
}

func (o *LinkClickedEventGeo) GetLv() *string {
	if o == nil {
		return nil
	}
	return o.Lv
}

func (o *LinkClickedEventGeo) GetLb() *string {
	if o == nil {
		return nil
	}
	return o.Lb
}

func (o *LinkClickedEventGeo) GetLs() *string {
	if o == nil {
		return nil
	}
	return o.Ls
}

func (o *LinkClickedEventGeo) GetLr() *string {
	if o == nil {
		return nil
	}
	return o.Lr
}

func (o *LinkClickedEventGeo) GetLy() *string {
	if o == nil {
		return nil
	}
	return o.Ly
}

func (o *LinkClickedEventGeo) GetLi() *string {
	if o == nil {
		return nil
	}
	return o.Li
}

func (o *LinkClickedEventGeo) GetLt() *string {
	if o == nil {
		return nil
	}
	return o.Lt
}

func (o *LinkClickedEventGeo) GetLu() *string {
	if o == nil {
		return nil
	}
	return o.Lu
}

func (o *LinkClickedEventGeo) GetMo() *string {
	if o == nil {
		return nil
	}
	return o.Mo
}

func (o *LinkClickedEventGeo) GetMg() *string {
	if o == nil {
		return nil
	}
	return o.Mg
}

func (o *LinkClickedEventGeo) GetMw() *string {
	if o == nil {
		return nil
	}
	return o.Mw
}

func (o *LinkClickedEventGeo) GetMy() *string {
	if o == nil {
		return nil
	}
	return o.My
}

func (o *LinkClickedEventGeo) GetMv() *string {
	if o == nil {
		return nil
	}
	return o.Mv
}

func (o *LinkClickedEventGeo) GetMl() *string {
	if o == nil {
		return nil
	}
	return o.Ml
}

func (o *LinkClickedEventGeo) GetMt() *string {
	if o == nil {
		return nil
	}
	return o.Mt
}

func (o *LinkClickedEventGeo) GetMh() *string {
	if o == nil {
		return nil
	}
	return o.Mh
}

func (o *LinkClickedEventGeo) GetMq() *string {
	if o == nil {
		return nil
	}
	return o.Mq
}

func (o *LinkClickedEventGeo) GetMr() *string {
	if o == nil {
		return nil
	}
	return o.Mr
}

func (o *LinkClickedEventGeo) GetMu() *string {
	if o == nil {
		return nil
	}
	return o.Mu
}

func (o *LinkClickedEventGeo) GetYt() *string {
	if o == nil {
		return nil
	}
	return o.Yt
}

func (o *LinkClickedEventGeo) GetMx() *string {
	if o == nil {
		return nil
	}
	return o.Mx
}

func (o *LinkClickedEventGeo) GetFm() *string {
	if o == nil {
		return nil
	}
	return o.Fm
}

func (o *LinkClickedEventGeo) GetMd() *string {
	if o == nil {
		return nil
	}
	return o.Md
}

func (o *LinkClickedEventGeo) GetMc() *string {
	if o == nil {
		return nil
	}
	return o.Mc
}

func (o *LinkClickedEventGeo) GetMn() *string {
	if o == nil {
		return nil
	}
	return o.Mn
}

func (o *LinkClickedEventGeo) GetMs() *string {
	if o == nil {
		return nil
	}
	return o.Ms
}

func (o *LinkClickedEventGeo) GetMa() *string {
	if o == nil {
		return nil
	}
	return o.Ma
}

func (o *LinkClickedEventGeo) GetMz() *string {
	if o == nil {
		return nil
	}
	return o.Mz
}

func (o *LinkClickedEventGeo) GetMm() *string {
	if o == nil {
		return nil
	}
	return o.Mm
}

func (o *LinkClickedEventGeo) GetNa() *string {
	if o == nil {
		return nil
	}
	return o.Na
}

func (o *LinkClickedEventGeo) GetNr() *string {
	if o == nil {
		return nil
	}
	return o.Nr
}

func (o *LinkClickedEventGeo) GetNp() *string {
	if o == nil {
		return nil
	}
	return o.Np
}

func (o *LinkClickedEventGeo) GetNl() *string {
	if o == nil {
		return nil
	}
	return o.Nl
}

func (o *LinkClickedEventGeo) GetNc() *string {
	if o == nil {
		return nil
	}
	return o.Nc
}

func (o *LinkClickedEventGeo) GetNz() *string {
	if o == nil {
		return nil
	}
	return o.Nz
}

func (o *LinkClickedEventGeo) GetNi() *string {
	if o == nil {
		return nil
	}
	return o.Ni
}

func (o *LinkClickedEventGeo) GetNe() *string {
	if o == nil {
		return nil
	}
	return o.Ne
}

func (o *LinkClickedEventGeo) GetNg() *string {
	if o == nil {
		return nil
	}
	return o.Ng
}

func (o *LinkClickedEventGeo) GetNu() *string {
	if o == nil {
		return nil
	}
	return o.Nu
}

func (o *LinkClickedEventGeo) GetNf() *string {
	if o == nil {
		return nil
	}
	return o.Nf
}

func (o *LinkClickedEventGeo) GetMk() *string {
	if o == nil {
		return nil
	}
	return o.Mk
}

func (o *LinkClickedEventGeo) GetMp() *string {
	if o == nil {
		return nil
	}
	return o.Mp
}

func (o *LinkClickedEventGeo) GetNo() *string {
	if o == nil {
		return nil
	}
	return o.No
}

func (o *LinkClickedEventGeo) GetOm() *string {
	if o == nil {
		return nil
	}
	return o.Om
}

func (o *LinkClickedEventGeo) GetPk() *string {
	if o == nil {
		return nil
	}
	return o.Pk
}

func (o *LinkClickedEventGeo) GetPw() *string {
	if o == nil {
		return nil
	}
	return o.Pw
}

func (o *LinkClickedEventGeo) GetPs() *string {
	if o == nil {
		return nil
	}
	return o.Ps
}

func (o *LinkClickedEventGeo) GetPa() *string {
	if o == nil {
		return nil
	}
	return o.Pa
}

func (o *LinkClickedEventGeo) GetPg() *string {
	if o == nil {
		return nil
	}
	return o.Pg
}

func (o *LinkClickedEventGeo) GetPy() *string {
	if o == nil {
		return nil
	}
	return o.Py
}

func (o *LinkClickedEventGeo) GetPe() *string {
	if o == nil {
		return nil
	}
	return o.Pe
}

func (o *LinkClickedEventGeo) GetPh() *string {
	if o == nil {
		return nil
	}
	return o.Ph
}

func (o *LinkClickedEventGeo) GetPn() *string {
	if o == nil {
		return nil
	}
	return o.Pn
}

func (o *LinkClickedEventGeo) GetPl() *string {
	if o == nil {
		return nil
	}
	return o.Pl
}

func (o *LinkClickedEventGeo) GetPt() *string {
	if o == nil {
		return nil
	}
	return o.Pt
}

func (o *LinkClickedEventGeo) GetPr() *string {
	if o == nil {
		return nil
	}
	return o.Pr
}

func (o *LinkClickedEventGeo) GetQa() *string {
	if o == nil {
		return nil
	}
	return o.Qa
}

func (o *LinkClickedEventGeo) GetRe() *string {
	if o == nil {
		return nil
	}
	return o.Re
}

func (o *LinkClickedEventGeo) GetRo() *string {
	if o == nil {
		return nil
	}
	return o.Ro
}

func (o *LinkClickedEventGeo) GetRu() *string {
	if o == nil {
		return nil
	}
	return o.Ru
}

func (o *LinkClickedEventGeo) GetRw() *string {
	if o == nil {
		return nil
	}
	return o.Rw
}

func (o *LinkClickedEventGeo) GetSh() *string {
	if o == nil {
		return nil
	}
	return o.Sh
}

func (o *LinkClickedEventGeo) GetKn() *string {
	if o == nil {
		return nil
	}
	return o.Kn
}

func (o *LinkClickedEventGeo) GetLc() *string {
	if o == nil {
		return nil
	}
	return o.Lc
}

func (o *LinkClickedEventGeo) GetPm() *string {
	if o == nil {
		return nil
	}
	return o.Pm
}

func (o *LinkClickedEventGeo) GetVc() *string {
	if o == nil {
		return nil
	}
	return o.Vc
}

func (o *LinkClickedEventGeo) GetWs() *string {
	if o == nil {
		return nil
	}
	return o.Ws
}

func (o *LinkClickedEventGeo) GetSm() *string {
	if o == nil {
		return nil
	}
	return o.Sm
}

func (o *LinkClickedEventGeo) GetSt() *string {
	if o == nil {
		return nil
	}
	return o.St
}

func (o *LinkClickedEventGeo) GetSa() *string {
	if o == nil {
		return nil
	}
	return o.Sa
}

func (o *LinkClickedEventGeo) GetSn() *string {
	if o == nil {
		return nil
	}
	return o.Sn
}

func (o *LinkClickedEventGeo) GetSc() *string {
	if o == nil {
		return nil
	}
	return o.Sc
}

func (o *LinkClickedEventGeo) GetSl() *string {
	if o == nil {
		return nil
	}
	return o.Sl
}

func (o *LinkClickedEventGeo) GetSg() *string {
	if o == nil {
		return nil
	}
	return o.Sg
}

func (o *LinkClickedEventGeo) GetSk() *string {
	if o == nil {
		return nil
	}
	return o.Sk
}

func (o *LinkClickedEventGeo) GetSi() *string {
	if o == nil {
		return nil
	}
	return o.Si
}

func (o *LinkClickedEventGeo) GetSb() *string {
	if o == nil {
		return nil
	}
	return o.Sb
}

func (o *LinkClickedEventGeo) GetSo() *string {
	if o == nil {
		return nil
	}
	return o.So
}

func (o *LinkClickedEventGeo) GetZa() *string {
	if o == nil {
		return nil
	}
	return o.Za
}

func (o *LinkClickedEventGeo) GetGs() *string {
	if o == nil {
		return nil
	}
	return o.Gs
}

func (o *LinkClickedEventGeo) GetEs() *string {
	if o == nil {
		return nil
	}
	return o.Es
}

func (o *LinkClickedEventGeo) GetLk() *string {
	if o == nil {
		return nil
	}
	return o.Lk
}

func (o *LinkClickedEventGeo) GetSd() *string {
	if o == nil {
		return nil
	}
	return o.Sd
}

func (o *LinkClickedEventGeo) GetSr() *string {
	if o == nil {
		return nil
	}
	return o.Sr
}

func (o *LinkClickedEventGeo) GetSj() *string {
	if o == nil {
		return nil
	}
	return o.Sj
}

func (o *LinkClickedEventGeo) GetSz() *string {
	if o == nil {
		return nil
	}
	return o.Sz
}

func (o *LinkClickedEventGeo) GetSe() *string {
	if o == nil {
		return nil
	}
	return o.Se
}

func (o *LinkClickedEventGeo) GetCh() *string {
	if o == nil {
		return nil
	}
	return o.Ch
}

func (o *LinkClickedEventGeo) GetSy() *string {
	if o == nil {
		return nil
	}
	return o.Sy
}

func (o *LinkClickedEventGeo) GetTw() *string {
	if o == nil {
		return nil
	}
	return o.Tw
}

func (o *LinkClickedEventGeo) GetTj() *string {
	if o == nil {
		return nil
	}
	return o.Tj
}

func (o *LinkClickedEventGeo) GetTz() *string {
	if o == nil {
		return nil
	}
	return o.Tz
}

func (o *LinkClickedEventGeo) GetTh() *string {
	if o == nil {
		return nil
	}
	return o.Th
}

func (o *LinkClickedEventGeo) GetTl() *string {
	if o == nil {
		return nil
	}
	return o.Tl
}

func (o *LinkClickedEventGeo) GetTg() *string {
	if o == nil {
		return nil
	}
	return o.Tg
}

func (o *LinkClickedEventGeo) GetTk() *string {
	if o == nil {
		return nil
	}
	return o.Tk
}

func (o *LinkClickedEventGeo) GetTo() *string {
	if o == nil {
		return nil
	}
	return o.To
}

func (o *LinkClickedEventGeo) GetTt() *string {
	if o == nil {
		return nil
	}
	return o.Tt
}

func (o *LinkClickedEventGeo) GetTn() *string {
	if o == nil {
		return nil
	}
	return o.Tn
}

func (o *LinkClickedEventGeo) GetTr() *string {
	if o == nil {
		return nil
	}
	return o.Tr
}

func (o *LinkClickedEventGeo) GetTm() *string {
	if o == nil {
		return nil
	}
	return o.Tm
}

func (o *LinkClickedEventGeo) GetTc() *string {
	if o == nil {
		return nil
	}
	return o.Tc
}

func (o *LinkClickedEventGeo) GetTv() *string {
	if o == nil {
		return nil
	}
	return o.Tv
}

func (o *LinkClickedEventGeo) GetUg() *string {
	if o == nil {
		return nil
	}
	return o.Ug
}

func (o *LinkClickedEventGeo) GetUa() *string {
	if o == nil {
		return nil
	}
	return o.Ua
}

func (o *LinkClickedEventGeo) GetAe() *string {
	if o == nil {
		return nil
	}
	return o.Ae
}

func (o *LinkClickedEventGeo) GetGb() *string {
	if o == nil {
		return nil
	}
	return o.Gb
}

func (o *LinkClickedEventGeo) GetUs() *string {
	if o == nil {
		return nil
	}
	return o.Us
}

func (o *LinkClickedEventGeo) GetUm() *string {
	if o == nil {
		return nil
	}
	return o.Um
}

func (o *LinkClickedEventGeo) GetUy() *string {
	if o == nil {
		return nil
	}
	return o.Uy
}

func (o *LinkClickedEventGeo) GetUz() *string {
	if o == nil {
		return nil
	}
	return o.Uz
}

func (o *LinkClickedEventGeo) GetVu() *string {
	if o == nil {
		return nil
	}
	return o.Vu
}

func (o *LinkClickedEventGeo) GetVe() *string {
	if o == nil {
		return nil
	}
	return o.Ve
}

func (o *LinkClickedEventGeo) GetVn() *string {
	if o == nil {
		return nil
	}
	return o.Vn
}

func (o *LinkClickedEventGeo) GetVg() *string {
	if o == nil {
		return nil
	}
	return o.Vg
}

func (o *LinkClickedEventGeo) GetVi() *string {
	if o == nil {
		return nil
	}
	return o.Vi
}

func (o *LinkClickedEventGeo) GetWf() *string {
	if o == nil {
		return nil
	}
	return o.Wf
}

func (o *LinkClickedEventGeo) GetEh() *string {
	if o == nil {
		return nil
	}
	return o.Eh
}

func (o *LinkClickedEventGeo) GetYe() *string {
	if o == nil {
		return nil
	}
	return o.Ye
}

func (o *LinkClickedEventGeo) GetZm() *string {
	if o == nil {
		return nil
	}
	return o.Zm
}

func (o *LinkClickedEventGeo) GetZw() *string {
	if o == nil {
		return nil
	}
	return o.Zw
}

func (o *LinkClickedEventGeo) GetAx() *string {
	if o == nil {
		return nil
	}
	return o.Ax
}

func (o *LinkClickedEventGeo) GetBq() *string {
	if o == nil {
		return nil
	}
	return o.Bq
}

func (o *LinkClickedEventGeo) GetCw() *string {
	if o == nil {
		return nil
	}
	return o.Cw
}

func (o *LinkClickedEventGeo) GetGg() *string {
	if o == nil {
		return nil
	}
	return o.Gg
}

func (o *LinkClickedEventGeo) GetIm() *string {
	if o == nil {
		return nil
	}
	return o.Im
}

func (o *LinkClickedEventGeo) GetJe() *string {
	if o == nil {
		return nil
	}
	return o.Je
}

func (o *LinkClickedEventGeo) GetMe() *string {
	if o == nil {
		return nil
	}
	return o.Me
}

func (o *LinkClickedEventGeo) GetBl() *string {
	if o == nil {
		return nil
	}
	return o.Bl
}

func (o *LinkClickedEventGeo) GetMf() *string {
	if o == nil {
		return nil
	}
	return o.Mf
}

func (o *LinkClickedEventGeo) GetRs() *string {
	if o == nil {
		return nil
	}
	return o.Rs
}

func (o *LinkClickedEventGeo) GetSx() *string {
	if o == nil {
		return nil
	}
	return o.Sx
}

func (o *LinkClickedEventGeo) GetSs() *string {
	if o == nil {
		return nil
	}
	return o.Ss
}

func (o *LinkClickedEventGeo) GetXk() *string {
	if o == nil {
		return nil
	}
	return o.Xk
}

type LinkClickedEventTestVariants struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (o *LinkClickedEventTestVariants) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LinkClickedEventTestVariants) GetPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Percentage
}

type LinkClickedEventLink struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key             string `json:"key"`
	URL             string `json:"url"`
	TrackConversion bool   `json:"trackConversion"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
	// The ID of the partner the short link is associated with.
	PartnerID  *string `json:"partnerId"`
	Archived   bool    `json:"archived"`
	ExpiresAt  string  `json:"expiresAt"`
	ExpiredURL *string `json:"expiredUrl"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password"`
	Proxy    bool    `json:"proxy"`
	// The title of the short link. Will be used for Custom Social Media Cards if `proxy` is true.
	Title *string `json:"title"`
	// The description of the short link. Will be used for Custom Social Media Cards if `proxy` is true.
	Description *string `json:"description"`
	// The image of the short link. Will be used for Custom Social Media Cards if `proxy` is true.
	Image *string `json:"image"`
	// The custom link preview video (og:video). Will be used for Custom Social Media Cards if `proxy` is true. Learn more: https://d.to/og
	Video   *string `json:"video"`
	Rewrite bool    `json:"rewrite"`
	DoIndex bool    `json:"doIndex"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
	Geo         *LinkClickedEventGeo `json:"geo"`
	PublicStats bool                 `json:"publicStats"`
	// The unique ID of the tag assigned to the short link. This field is deprecated – use `tags` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId"`
	// The tags assigned to the short link.
	Tags []TagSchema `json:"tags"`
	// The unique ID of the folder assigned to the short link.
	FolderID *string `json:"folderId"`
	// The IDs of the webhooks that the short link is associated with.
	WebhookIds []string `json:"webhookIds"`
	// The comments for the short link.
	Comments *string `json:"comments"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The full URL of the QR code for the short link (e.g. `https://api.dub.co/qr?url=https://dub.sh/try`).
	QrCode string `json:"qrCode"`
	// The UTM source of the short link.
	UtmSource *string `json:"utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `json:"utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `json:"utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `json:"utm_term"`
	// The UTM content of the short link.
	UtmContent *string `json:"utm_content"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants    []LinkClickedEventTestVariants `json:"testVariants,omitempty"`
	TestStartedAt   *string                        `json:"testStartedAt"`
	TestCompletedAt *string                        `json:"testCompletedAt"`
	UserID          *string                        `json:"userId"`
	// The workspace ID of the short link.
	WorkspaceID string `json:"workspaceId"`
	// The number of clicks on the short link.
	Clicks      *float64 `default:"0" json:"clicks"`
	LastClicked string   `json:"lastClicked"`
	// The number of leads the short links has generated.
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales the short links has generated.
	Sales *float64 `default:"0" json:"sales"`
	// The total dollar amount of sales the short links has generated (in cents).
	SaleAmount *float64 `default:"0" json:"saleAmount"`
	CreatedAt  string   `json:"createdAt"`
	UpdatedAt  string   `json:"updatedAt"`
	// The project ID of the short link. This field is deprecated – use `workspaceId` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectID string `json:"projectId"`
}

func (l LinkClickedEventLink) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkClickedEventLink) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *LinkClickedEventLink) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LinkClickedEventLink) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *LinkClickedEventLink) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *LinkClickedEventLink) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LinkClickedEventLink) GetTrackConversion() bool {
	if o == nil {
		return false
	}
	return o.TrackConversion
}

func (o *LinkClickedEventLink) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *LinkClickedEventLink) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *LinkClickedEventLink) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *LinkClickedEventLink) GetPartnerID() *string {
	if o == nil {
		return nil
	}
	return o.PartnerID
}

func (o *LinkClickedEventLink) GetArchived() bool {
	if o == nil {
		return false
	}
	return o.Archived
}

func (o *LinkClickedEventLink) GetExpiresAt() string {
	if o == nil {
		return ""
	}
	return o.ExpiresAt
}

func (o *LinkClickedEventLink) GetExpiredURL() *string {
	if o == nil {
		return nil
	}
	return o.ExpiredURL
}

func (o *LinkClickedEventLink) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *LinkClickedEventLink) GetProxy() bool {
	if o == nil {
		return false
	}
	return o.Proxy
}

func (o *LinkClickedEventLink) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *LinkClickedEventLink) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *LinkClickedEventLink) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *LinkClickedEventLink) GetVideo() *string {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *LinkClickedEventLink) GetRewrite() bool {
	if o == nil {
		return false
	}
	return o.Rewrite
}

func (o *LinkClickedEventLink) GetDoIndex() bool {
	if o == nil {
		return false
	}
	return o.DoIndex
}

func (o *LinkClickedEventLink) GetIos() *string {
	if o == nil {
		return nil
	}
	return o.Ios
}

func (o *LinkClickedEventLink) GetAndroid() *string {
	if o == nil {
		return nil
	}
	return o.Android
}

func (o *LinkClickedEventLink) GetGeo() *LinkClickedEventGeo {
	if o == nil {
		return nil
	}
	return o.Geo
}

func (o *LinkClickedEventLink) GetPublicStats() bool {
	if o == nil {
		return false
	}
	return o.PublicStats
}

func (o *LinkClickedEventLink) GetTagID() *string {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *LinkClickedEventLink) GetTags() []TagSchema {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *LinkClickedEventLink) GetFolderID() *string {
	if o == nil {
		return nil
	}
	return o.FolderID
}

func (o *LinkClickedEventLink) GetWebhookIds() []string {
	if o == nil {
		return []string{}
	}
	return o.WebhookIds
}

func (o *LinkClickedEventLink) GetComments() *string {
	if o == nil {
		return nil
	}
	return o.Comments
}

func (o *LinkClickedEventLink) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *LinkClickedEventLink) GetQrCode() string {
	if o == nil {
		return ""
	}
	return o.QrCode
}

func (o *LinkClickedEventLink) GetUtmSource() *string {
	if o == nil {
		return nil
	}
	return o.UtmSource
}

func (o *LinkClickedEventLink) GetUtmMedium() *string {
	if o == nil {
		return nil
	}
	return o.UtmMedium
}

func (o *LinkClickedEventLink) GetUtmCampaign() *string {
	if o == nil {
		return nil
	}
	return o.UtmCampaign
}

func (o *LinkClickedEventLink) GetUtmTerm() *string {
	if o == nil {
		return nil
	}
	return o.UtmTerm
}

func (o *LinkClickedEventLink) GetUtmContent() *string {
	if o == nil {
		return nil
	}
	return o.UtmContent
}

func (o *LinkClickedEventLink) GetTestVariants() []LinkClickedEventTestVariants {
	if o == nil {
		return nil
	}
	return o.TestVariants
}

func (o *LinkClickedEventLink) GetTestStartedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestStartedAt
}

func (o *LinkClickedEventLink) GetTestCompletedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestCompletedAt
}

func (o *LinkClickedEventLink) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *LinkClickedEventLink) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *LinkClickedEventLink) GetClicks() *float64 {
	if o == nil {
		return nil
	}
	return o.Clicks
}

func (o *LinkClickedEventLink) GetLastClicked() string {
	if o == nil {
		return ""
	}
	return o.LastClicked
}

func (o *LinkClickedEventLink) GetLeads() *float64 {
	if o == nil {
		return nil
	}
	return o.Leads
}

func (o *LinkClickedEventLink) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *LinkClickedEventLink) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *LinkClickedEventLink) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *LinkClickedEventLink) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *LinkClickedEventLink) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type Data struct {
	Click LinkClickedEventClick `json:"click"`
	Link  LinkClickedEventLink  `json:"link"`
}

func (o *Data) GetClick() LinkClickedEventClick {
	if o == nil {
		return LinkClickedEventClick{}
	}
	return o.Click
}

func (o *Data) GetLink() LinkClickedEventLink {
	if o == nil {
		return LinkClickedEventLink{}
	}
	return o.Link
}

// LinkClickedEvent - Triggered when a link is clicked.
type LinkClickedEvent struct {
	ID        string                `json:"id"`
	Event     LinkClickedEventEvent `json:"event"`
	CreatedAt string                `json:"createdAt"`
	Data      Data                  `json:"data"`
}

func (o *LinkClickedEvent) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LinkClickedEvent) GetEvent() LinkClickedEventEvent {
	if o == nil {
		return LinkClickedEventEvent("")
	}
	return o.Event
}

func (o *LinkClickedEvent) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *LinkClickedEvent) GetData() Data {
	if o == nil {
		return Data{}
	}
	return o.Data
}
