/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyticsBrowsers = {
  /**
   * The name of the browser
   */
  browser: string;
  /**
   * The number of clicks from this browser
   */
  clicks?: number | undefined;
  /**
   * The number of leads from this browser
   */
  leads?: number | undefined;
  /**
   * The number of sales from this browser
   */
  sales?: number | undefined;
  /**
   * The total amount of sales from this browser, in cents
   */
  saleAmount?: number | undefined;
};

/** @internal */
export const AnalyticsBrowsers$inboundSchema: z.ZodType<
  AnalyticsBrowsers,
  z.ZodTypeDef,
  unknown
> = z.object({
  browser: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
});

/** @internal */
export type AnalyticsBrowsers$Outbound = {
  browser: string;
  clicks: number;
  leads: number;
  sales: number;
  saleAmount: number;
};

/** @internal */
export const AnalyticsBrowsers$outboundSchema: z.ZodType<
  AnalyticsBrowsers$Outbound,
  z.ZodTypeDef,
  AnalyticsBrowsers
> = z.object({
  browser: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyticsBrowsers$ {
  /** @deprecated use `AnalyticsBrowsers$inboundSchema` instead. */
  export const inboundSchema = AnalyticsBrowsers$inboundSchema;
  /** @deprecated use `AnalyticsBrowsers$outboundSchema` instead. */
  export const outboundSchema = AnalyticsBrowsers$outboundSchema;
  /** @deprecated use `AnalyticsBrowsers$Outbound` instead. */
  export type Outbound = AnalyticsBrowsers$Outbound;
}

export function analyticsBrowsersToJSON(
  analyticsBrowsers: AnalyticsBrowsers,
): string {
  return JSON.stringify(
    AnalyticsBrowsers$outboundSchema.parse(analyticsBrowsers),
  );
}

export function analyticsBrowsersFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsBrowsers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsBrowsers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsBrowsers' from JSON`,
  );
}
