/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The 2-letter country code of the region: https://d.to/geo
 */
export const AnalyticsRegionsCountry = {
  Af: "AF",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kp: "KP",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mk: "MK",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Ax: "AX",
  Bq: "BQ",
  Cw: "CW",
  Gg: "GG",
  Im: "IM",
  Je: "JE",
  Me: "ME",
  Bl: "BL",
  Mf: "MF",
  Rs: "RS",
  Sx: "SX",
  Ss: "SS",
  Xk: "XK",
} as const;
/**
 * The 2-letter country code of the region: https://d.to/geo
 */
export type AnalyticsRegionsCountry = ClosedEnum<
  typeof AnalyticsRegionsCountry
>;

export const AnalyticsRegionsCity = {
  Wildcard: "*",
} as const;
export type AnalyticsRegionsCity = ClosedEnum<typeof AnalyticsRegionsCity>;

export type AnalyticsRegions = {
  /**
   * The 2-letter country code of the region: https://d.to/geo
   */
  country: AnalyticsRegionsCountry;
  /**
   * The 2-letter ISO 3166-2 region code representing the region associated with the location of the user.
   */
  region: string;
  city?: AnalyticsRegionsCity | undefined;
  /**
   * The number of clicks from this region
   */
  clicks?: number | undefined;
  /**
   * The number of leads from this region
   */
  leads?: number | undefined;
  /**
   * The number of sales from this region
   */
  sales?: number | undefined;
  /**
   * The total amount of sales from this region, in cents
   */
  saleAmount?: number | undefined;
};

/** @internal */
export const AnalyticsRegionsCountry$inboundSchema: z.ZodNativeEnum<
  typeof AnalyticsRegionsCountry
> = z.nativeEnum(AnalyticsRegionsCountry);

/** @internal */
export const AnalyticsRegionsCountry$outboundSchema: z.ZodNativeEnum<
  typeof AnalyticsRegionsCountry
> = AnalyticsRegionsCountry$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyticsRegionsCountry$ {
  /** @deprecated use `AnalyticsRegionsCountry$inboundSchema` instead. */
  export const inboundSchema = AnalyticsRegionsCountry$inboundSchema;
  /** @deprecated use `AnalyticsRegionsCountry$outboundSchema` instead. */
  export const outboundSchema = AnalyticsRegionsCountry$outboundSchema;
}

/** @internal */
export const AnalyticsRegionsCity$inboundSchema: z.ZodNativeEnum<
  typeof AnalyticsRegionsCity
> = z.nativeEnum(AnalyticsRegionsCity);

/** @internal */
export const AnalyticsRegionsCity$outboundSchema: z.ZodNativeEnum<
  typeof AnalyticsRegionsCity
> = AnalyticsRegionsCity$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyticsRegionsCity$ {
  /** @deprecated use `AnalyticsRegionsCity$inboundSchema` instead. */
  export const inboundSchema = AnalyticsRegionsCity$inboundSchema;
  /** @deprecated use `AnalyticsRegionsCity$outboundSchema` instead. */
  export const outboundSchema = AnalyticsRegionsCity$outboundSchema;
}

/** @internal */
export const AnalyticsRegions$inboundSchema: z.ZodType<
  AnalyticsRegions,
  z.ZodTypeDef,
  unknown
> = z.object({
  country: AnalyticsRegionsCountry$inboundSchema,
  region: z.string(),
  city: AnalyticsRegionsCity$inboundSchema.default("*"),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
});

/** @internal */
export type AnalyticsRegions$Outbound = {
  country: string;
  region: string;
  city: string;
  clicks: number;
  leads: number;
  sales: number;
  saleAmount: number;
};

/** @internal */
export const AnalyticsRegions$outboundSchema: z.ZodType<
  AnalyticsRegions$Outbound,
  z.ZodTypeDef,
  AnalyticsRegions
> = z.object({
  country: AnalyticsRegionsCountry$outboundSchema,
  region: z.string(),
  city: AnalyticsRegionsCity$outboundSchema.default("*"),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnalyticsRegions$ {
  /** @deprecated use `AnalyticsRegions$inboundSchema` instead. */
  export const inboundSchema = AnalyticsRegions$inboundSchema;
  /** @deprecated use `AnalyticsRegions$outboundSchema` instead. */
  export const outboundSchema = AnalyticsRegions$outboundSchema;
  /** @deprecated use `AnalyticsRegions$Outbound` instead. */
  export type Outbound = AnalyticsRegions$Outbound;
}

export function analyticsRegionsToJSON(
  analyticsRegions: AnalyticsRegions,
): string {
  return JSON.stringify(
    AnalyticsRegions$outboundSchema.parse(analyticsRegions),
  );
}

export function analyticsRegionsFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsRegions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsRegions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsRegions' from JSON`,
  );
}
