/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ClicksTopLinks = {
    /**
     * The unique ID of the short link
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    link: string;
    /**
     * The unique ID of the short link
     */
    id: string;
    /**
     * The domain of the short link
     */
    domain: string;
    /**
     * The key of the short link
     */
    key: string;
    /**
     * The short link URL
     */
    shortLink: string;
    /**
     * The destination URL of the short link
     */
    url: string;
    /**
     * The creation timestamp of the short link
     */
    createdAt: string;
    /**
     * The number of clicks from this link
     */
    clicks: number;
};

/** @internal */
export namespace ClicksTopLinks$ {
    export const inboundSchema: z.ZodType<ClicksTopLinks, z.ZodTypeDef, unknown> = z.object({
        link: z.string(),
        id: z.string(),
        domain: z.string(),
        key: z.string(),
        shortLink: z.string(),
        url: z.string(),
        createdAt: z.string(),
        clicks: z.number(),
    });

    export type Outbound = {
        link: string;
        id: string;
        domain: string;
        key: string;
        shortLink: string;
        url: string;
        createdAt: string;
        clicks: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ClicksTopLinks> = z.object({
        link: z.string(),
        id: z.string(),
        domain: z.string(),
        key: z.string(),
        shortLink: z.string(),
        url: z.string(),
        createdAt: z.string(),
        clicks: z.number(),
    });
}
