/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A short code indicating the error code returned.
 */
export const ForbiddenCode = {
    Forbidden: "forbidden",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type ForbiddenCode = (typeof ForbiddenCode)[keyof typeof ForbiddenCode];

export type ForbiddenError = {
    /**
     * A short code indicating the error code returned.
     */
    code: ForbiddenCode;
    /**
     * A human readable explanation of what went wrong.
     */
    message: string;
    /**
     * A link to our documentation with more details about this error code
     */
    docUrl?: string | undefined;
};

export type Forbidden = {
    error: ForbiddenError;
};

/** @internal */
export const ForbiddenCode$: z.ZodNativeEnum<typeof ForbiddenCode> = z.nativeEnum(ForbiddenCode);

/** @internal */
export namespace ForbiddenError$ {
    export type Inbound = {
        code: ForbiddenCode;
        message: string;
        doc_url?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ForbiddenError, z.ZodTypeDef, Inbound> = z
        .object({
            code: ForbiddenCode$,
            message: z.string(),
            doc_url: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                message: v.message,
                ...(v.doc_url === undefined ? null : { docUrl: v.doc_url }),
            };
        });

    export type Outbound = {
        code: ForbiddenCode;
        message: string;
        doc_url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ForbiddenError> = z
        .object({
            code: ForbiddenCode$,
            message: z.string(),
            docUrl: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                message: v.message,
                ...(v.docUrl === undefined ? null : { doc_url: v.docUrl }),
            };
        });
}

/** @internal */
export namespace Forbidden$ {
    export type Inbound = {
        error: ForbiddenError$.Inbound;
    };

    export const inboundSchema: z.ZodType<Forbidden, z.ZodTypeDef, Inbound> = z
        .object({
            error: z.lazy(() => ForbiddenError$.inboundSchema),
        })
        .transform((v) => {
            return {
                error: v.error,
            };
        });

    export type Outbound = {
        error: ForbiddenError$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Forbidden> = z
        .object({
            error: z.lazy(() => ForbiddenError$.outboundSchema),
        })
        .transform((v) => {
            return {
                error: v.error,
            };
        });
}
