/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LeadEvents = {
    timestamp: string;
    eventId: string;
    eventName: string;
    customerName: string;
    customerEmail: string;
    customerAvatar: string;
    clickId: string;
    linkId: string;
    domain: string;
    key: string;
    url: string;
    continent: string | null;
    country: string | null;
    city: string | null;
    device: string | null;
    browser: string | null;
    os: string | null;
    referer: string | null;
    qr: number | null;
    ip: string | null;
};

/** @internal */
export const LeadEvents$inboundSchema: z.ZodType<LeadEvents, z.ZodTypeDef, unknown> = z
    .object({
        timestamp: z.string(),
        event_id: z.string(),
        event_name: z.string(),
        customer_name: z.string(),
        customer_email: z.string(),
        customer_avatar: z.string(),
        click_id: z.string(),
        link_id: z.string(),
        domain: z.string(),
        key: z.string(),
        url: z.string(),
        continent: z.nullable(z.string()),
        country: z.nullable(z.string()),
        city: z.nullable(z.string()),
        device: z.nullable(z.string()),
        browser: z.nullable(z.string()),
        os: z.nullable(z.string()),
        referer: z.nullable(z.string()),
        qr: z.nullable(z.number()),
        ip: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            event_id: "eventId",
            event_name: "eventName",
            customer_name: "customerName",
            customer_email: "customerEmail",
            customer_avatar: "customerAvatar",
            click_id: "clickId",
            link_id: "linkId",
        });
    });

/** @internal */
export type LeadEvents$Outbound = {
    timestamp: string;
    event_id: string;
    event_name: string;
    customer_name: string;
    customer_email: string;
    customer_avatar: string;
    click_id: string;
    link_id: string;
    domain: string;
    key: string;
    url: string;
    continent: string | null;
    country: string | null;
    city: string | null;
    device: string | null;
    browser: string | null;
    os: string | null;
    referer: string | null;
    qr: number | null;
    ip: string | null;
};

/** @internal */
export const LeadEvents$outboundSchema: z.ZodType<LeadEvents$Outbound, z.ZodTypeDef, LeadEvents> = z
    .object({
        timestamp: z.string(),
        eventId: z.string(),
        eventName: z.string(),
        customerName: z.string(),
        customerEmail: z.string(),
        customerAvatar: z.string(),
        clickId: z.string(),
        linkId: z.string(),
        domain: z.string(),
        key: z.string(),
        url: z.string(),
        continent: z.nullable(z.string()),
        country: z.nullable(z.string()),
        city: z.nullable(z.string()),
        device: z.nullable(z.string()),
        browser: z.nullable(z.string()),
        os: z.nullable(z.string()),
        referer: z.nullable(z.string()),
        qr: z.nullable(z.number()),
        ip: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            eventId: "event_id",
            eventName: "event_name",
            customerName: "customer_name",
            customerEmail: "customer_email",
            customerAvatar: "customer_avatar",
            clickId: "click_id",
            linkId: "link_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LeadEvents$ {
    /** @deprecated use `LeadEvents$inboundSchema` instead. */
    export const inboundSchema = LeadEvents$inboundSchema;
    /** @deprecated use `LeadEvents$outboundSchema` instead. */
    export const outboundSchema = LeadEvents$outboundSchema;
    /** @deprecated use `LeadEvents$Outbound` instead. */
    export type Outbound = LeadEvents$Outbound;
}
