/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PartnerAnalyticsTimeseries = {
  /**
   * The starting timestamp of the interval
   */
  start: string;
  /**
   * The number of clicks in the interval
   */
  clicks?: number | undefined;
  /**
   * The number of leads in the interval
   */
  leads?: number | undefined;
  /**
   * The number of sales in the interval
   */
  sales?: number | undefined;
  /**
   * The total amount of sales in the interval, in cents
   */
  saleAmount?: number | undefined;
  earnings?: number | undefined;
};

/** @internal */
export const PartnerAnalyticsTimeseries$inboundSchema: z.ZodType<
  PartnerAnalyticsTimeseries,
  z.ZodTypeDef,
  unknown
> = z.object({
  start: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
  earnings: z.number().default(0),
});

/** @internal */
export type PartnerAnalyticsTimeseries$Outbound = {
  start: string;
  clicks: number;
  leads: number;
  sales: number;
  saleAmount: number;
  earnings: number;
};

/** @internal */
export const PartnerAnalyticsTimeseries$outboundSchema: z.ZodType<
  PartnerAnalyticsTimeseries$Outbound,
  z.ZodTypeDef,
  PartnerAnalyticsTimeseries
> = z.object({
  start: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  sales: z.number().default(0),
  saleAmount: z.number().default(0),
  earnings: z.number().default(0),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PartnerAnalyticsTimeseries$ {
  /** @deprecated use `PartnerAnalyticsTimeseries$inboundSchema` instead. */
  export const inboundSchema = PartnerAnalyticsTimeseries$inboundSchema;
  /** @deprecated use `PartnerAnalyticsTimeseries$outboundSchema` instead. */
  export const outboundSchema = PartnerAnalyticsTimeseries$outboundSchema;
  /** @deprecated use `PartnerAnalyticsTimeseries$Outbound` instead. */
  export type Outbound = PartnerAnalyticsTimeseries$Outbound;
}

export function partnerAnalyticsTimeseriesToJSON(
  partnerAnalyticsTimeseries: PartnerAnalyticsTimeseries,
): string {
  return JSON.stringify(
    PartnerAnalyticsTimeseries$outboundSchema.parse(partnerAnalyticsTimeseries),
  );
}

export function partnerAnalyticsTimeseriesFromJSON(
  jsonString: string,
): SafeParseResult<PartnerAnalyticsTimeseries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PartnerAnalyticsTimeseries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartnerAnalyticsTimeseries' from JSON`,
  );
}
